### ISSUE TITLE
Jasperreports - error sending mail

### ISSUE THREAD

**Issue by criticalboot** [bitnami/containers#10168]
### Name and Version

bitnami/jasperreports:8.1.0

### What steps will reproduce the bug?

```
ENV: 
"JASPERREPORTS_EMAIL=myemail@gmail.com",
"MYSQL_CLIENT_DATABASE_HOST=mariadb",
"MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306",
"MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=*****",
"MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_jasperreports",
"MYSQL_CLIENT_CREATE_DATABASE_USER=bn_jasperreports",
"MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=*******",
"JASPERREPORTS_DATABASE_PASSWORD=*******",
"JASPERREPORTS_SMTP_HOST=smtp.gmail.com",
"JASPERREPORTS_SMTP_PORT_NUMBER=587",
"JASPERREPORTS_SMTP_USER=myemail@gmail.com",
"JASPERREPORTS_SMTP_PASSWORD=**********",
"JASPERREPORTS_SMTP_PROTOCOL=smtp",
"PATH=/opt/bitnami/java/bin:/opt/bitnami/tomcat/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/mysql/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"HOME=/",
"OS_ARCH=amd64",
"OS_FLAVOUR=debian-11",
"OS_NAME=linux",
"APP_VERSION=8.1.0",
"BITNAMI_APP_NAME=jasperreports",
"JAVA_HOME=/opt/bitnami/java"
```

### What do you see instead?

```
jasperreports_1  | 2022-10-15T07:16:29,058 ERROR SecureExceptionHandlerImpl,JasperServerScheduler_Worker-1:125 - There was an error on the server. Try again or contact site administrators. (Error UID: 9d0c0948-7294-421d-993e-3c5931581c9d) org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. ij4-20020a170902ab4400b0017f8edd3d8asm2739335plb.177 - gsmtp
jasperreports_1  | ; message exception details (1) are:
jasperreports_1  | Failed message 1:
jasperreports_1  | com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. ij4-20020a170902ab4400b0017f8edd3d8asm2739335plb.177 - gsmtp
jasperreports_1  | 
jasperreports_1  | 	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2358)
jasperreports_1  | 	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1823)
jasperreports_1  | 	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)
jasperreports_1  | 	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:465)
jasperreports_1  | 	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
jasperreports_1  | 	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
jasperreports_1  | 	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJobMailNotificationImpl.sendMailNotification(ReportExecutionJobMailNotificationImpl.java:141)
jasperreports_1  | 	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.sendMailNotification(ReportExecutionJob.java:884)
jasperreports_1  | 	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.executeAndSendReport(ReportExecutionJob.java:658)
jasperreports_1  | 	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.execute(ReportExecutionJob.java:309)
jasperreports_1  | 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
jasperreports_1  | 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
jasperreports_1  | 
```

**Comment by recena** [comment]
@criticalboot Did you try with other SMTP server?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by criticalboot** [comment]
@recena, Not tried other than Gmail. Mail is working last week after updating it failed.
