### ISSUE TITLE
After shutdown and restart of kubernetes cluster, etcd don't start

### ISSUE THREAD

**Issue by MirtoBusico** [bitnami/containers#19824]
### Name and Version

from the log: "Welcome to the Bitnami etcd container"

### What steps will reproduce the bug?

1. environment: 1 master + 3 worker K3S nodes. Istio. Longhorn storage. 
2. install apisix via helm chart (installs 3 nodes etcd using the bitnami chart)
3. for some months shutdown and restart the cluster daily
4. suddenly etcd pods don't start giving errors

### What is the expected behavior?

The pod start correctly

### What do you see instead?

All the 3 pods gives these error logs:

```
2023-01-11T09:39:54.066Z | [38;5;6metcd [38;5;5m09:39:54.06 [0m
2023-01-11T09:39:54.067Z | [38;5;6metcd [38;5;5m09:39:54.06 [0m[1mWelcome to the Bitnami etcd container[0m
2023-01-11T09:39:54.067Z | [38;5;6metcd [38;5;5m09:39:54.06 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
2023-01-11T09:39:54.068Z | [38;5;6metcd [38;5;5m09:39:54.06 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
2023-01-11T09:39:54.069Z | [38;5;6metcd [38;5;5m09:39:54.06 [0m
2023-01-11T09:39:54.069Z | [38;5;6metcd [38;5;5m09:39:54.06 [0m[38;5;2mINFO [0m ==> ** Starting etcd setup **
2023-01-11T09:39:54.075Z | [38;5;6metcd [38;5;5m09:39:54.07 [0m[38;5;2mINFO [0m ==> Validating settings in ETCD_* env vars..
2023-01-11T09:39:54.076Z | [38;5;6metcd [38;5;5m09:39:54.07 [0m[38;5;3mWARN [0m ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
2023-01-11T09:39:54.078Z | [38;5;6metcd [38;5;5m09:39:54.07 [0m[38;5;2mINFO [0m ==> Initializing etcd
2023-01-11T09:39:54.078Z | [38;5;6metcd [38;5;5m09:39:54.07 [0m[38;5;2mINFO [0m ==> Generating etcd config file using env variables
2023-01-11T09:39:54.085Z | [38;5;6metcd [38;5;5m09:39:54.08 [0m[38;5;2mINFO [0m ==> Detected data from previous deployments
2023-01-11T09:40:04.143Z | [38;5;6metcd [38;5;5m09:40:04.14 [0m[38;5;3mWARN [0m ==> Cluster not responding!
2023-01-11T09:40:04.144Z | [38;5;6metcd [38;5;5m09:40:04.14 [0m[38;5;3mWARN [0m ==> Disaster recovery is disabled, the cluster will try to recover on it's own
2023-01-11T09:40:04.147Z |
2023-01-11T09:40:04.147Z | [38;5;6metcd [38;5;5m09:40:04.14 [0m[38;5;2mINFO [0m ==> ** etcd setup finished! **
2023-01-11T09:40:04.155Z | [38;5;6metcd [38;5;5m09:40:04.15 [0m[38;5;2mINFO [0m ==> ** Starting etcd **
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_ADVERTISE_CLIENT_URLS","variable-value":"http://apisix-etcd-0.apisix-etcd-headless.apisix.svc.cluster.local:2379,http://apisix-etcd.apisix.svc.cluster.local:2379"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTH_TOKEN","variable-value":"jwt,priv-key=/opt/bitnami/etcd/certs/token/jwt-token.pem,sign-method=RS256,ttl=10m"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTO_TLS","variable-value":"false"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_CLIENT_CERT_AUTH","variable-value":"false"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_DATA_DIR","variable-value":"/bitnami/etcd/data"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_ADVERTISE_PEER_URLS","variable-value":"http://apisix-etcd-0.apisix-etcd-headless.apisix.svc.cluster.local:2380"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER","variable-value":"apisix-etcd-0=http://apisix-etcd-0.apisix-etcd-headless.apisix.svc.cluster.local:2380,apisix-etcd-1=http://apisix-etcd-1.apisix-etcd-headless.apisix.svc.cluster.local:2380,apisix-etcd-2=http://apisix-etcd-2.apisix-etcd-headless.apisix.svc.cluster.local:2380"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER_STATE","variable-value":"new"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER_TOKEN","variable-value":"etcd-cluster-k8s"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LISTEN_CLIENT_URLS","variable-value":"http://0.0.0.0:2379"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LISTEN_PEER_URLS","variable-value":"http://0.0.0.0:2380"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LOG_LEVEL","variable-value":"info"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_NAME","variable-value":"apisix-etcd-0"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_PEER_AUTO_TLS","variable-value":"false"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TRUSTED_CA_FILE="}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DISABLE_STORE_MEMBER_ID=no"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CONF_FILE=/opt/bitnami/etcd/conf/etcd.yaml"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_ON_K8S=yes"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_SNAPSHOTS_DIR=/snapshots"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_BIN_DIR=/opt/bitnami/etcd/bin"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_VOLUME_DIR=/bitnami/etcd"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_ROOT_PASSWORD="}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CLUSTER_DOMAIN=apisix-etcd-headless.apisix.svc.cluster.local"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DISASTER_RECOVERY=no"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_KEY_FILE="}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CONF_DIR=/opt/bitnami/etcd/conf"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DAEMON_GROUP=etcd"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_START_FROM_SNAPSHOT=no"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_INIT_SNAPSHOT_FILENAME="}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_INIT_SNAPSHOTS_DIR=/init-snapshot"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DISABLE_PRESTOP=no"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TMP_DIR=/opt/bitnami/etcd/tmp"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_BASE_DIR=/opt/bitnami/etcd"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CERT_FILE="}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_NEW_MEMBERS_ENV_FILE=/bitnami/etcd/data/new_member_envs"}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DAEMON_USER=etcd"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"etcdmain/etcd.go:73","msg":"Running: ","args":["etcd"]}
2023-01-11T09:40:04.163Z | {"level":"warn","ts":"2023-01-11T09:40:04.163Z","caller":"etcdmain/etcd.go:446","msg":"found invalid file under data directory","filename":"member_id","data-dir":"/bitnami/etcd/data"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"etcdmain/etcd.go:116","msg":"server has been already initialized","data-dir":"/bitnami/etcd/data","dir-type":"member"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://0.0.0.0:2380"]}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://0.0.0.0:2379"]}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4","git-sha":"08407ff76","go-version":"go1.16.15","go-os":"linux","go-arch":"amd64","max-cpu-set":6,"max-cpu-available":6,"member-initialized":true,"name":"apisix-etcd-0","data-dir":"/bitnami/etcd/data","wal-dir":"","wal-dir-dedicated":"","member-dir":"/bitnami/etcd/data/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://apisix-etcd-0.apisix-etcd-headless.apisix.svc.cluster.local:2380"],"listen-peer-urls":["http://0.0.0.0:2380"],"advertise-client-urls":["http://apisix-etcd-0.apisix-etcd-headless.apisix.svc.cluster.local:2379","http://apisix-etcd.apisix.svc.cluster.local:2379"],"listen-client-urls":["http://0.0.0.0:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
2023-01-11T09:40:04.163Z | {"level":"info","ts":"2023-01-11T09:40:04.163Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/bitnami/etcd/data/member/snap/db","took":"219.638µs"}
2023-01-11T09:40:04.479Z | {"level":"info","ts":"2023-01-11T09:40:04.479Z","caller":"etcdserver/server.go:508","msg":"recovered v2 store from snapshot","snapshot-index":600006,"snapshot-size":"26 kB"}
2023-01-11T09:40:04.480Z | {"level":"warn","ts":"2023-01-11T09:40:04.480Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":600006,"snapshot-file-path":"/bitnami/etcd/data/member/snap/00000000000927c6.snap.db","error":"snap: snapshot file doesn't exist"}
2023-01-11T09:40:04.480Z | {"level":"panic","ts":"2023-01-11T09:40:04.480Z","caller":"etcdserver/server.go:515","msg":"failed to recover v3 backend from snapshot","error":"failed to find database snapshot file (snap: snapshot file doesn't exist)","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.NewServer\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdserver/server.go:515\ngo.etcd.io/etcd/server/v3/embed.StartEtcd\n\t/go/src/go.etcd.io/etcd/release/etcd/server/embed/etcd.go:245\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcd\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:228\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:123\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/go/gos/go1.16.15/src/runtime/proc.go:225"}
2023-01-11T09:40:04.483Z | panic: failed to recover v3 backend from snapshot
2023-01-11T09:40:04.483Z |
2023-01-11T09:40:04.483Z | goroutine 1 [running]:
2023-01-11T09:40:04.483Z | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000208600, 0xc0000a5940, 0x1, 0x1)
2023-01-11T09:40:04.483Z | /go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x58d
2023-01-11T09:40:04.483Z | go.uber.org/zap.(*Logger).Panic(0xc0004865a0, 0x1234726, 0x2a, 0xc0000a5940, 0x1, 0x1)
2023-01-11T09:40:04.483Z | /go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:227 +0x85
2023-01-11T09:40:04.483Z | go.etcd.io/etcd/server/v3/etcdserver.NewServer(0xc0000440b2, 0xd, 0x0, 0x0, 0x0, 0x0, 0xc0000c06c0, 0x2, 0x2, 0xc0002326c0, ...)
2023-01-11T09:40:04.483Z | /go/src/go.etcd.io/etcd/release/etcd/server/etcdserver/server.go:515 +0x1656
2023-01-11T09:40:04.483Z | go.etcd.io/etcd/server/v3/embed.StartEtcd(0xc000596000, 0xc000596600, 0x0, 0x0)
2023-01-11T09:40:04.483Z | /go/src/go.etcd.io/etcd/release/etcd/server/embed/etcd.go:245 +0xef8
2023-01-11T09:40:04.483Z | go.etcd.io/etcd/server/v3/etcdmain.startEtcd(0xc000596000, 0x12089be, 0x6, 0xc0000f4c01, 0x2)
2023-01-11T09:40:04.483Z | /go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:228 +0x32
2023-01-11T09:40:04.483Z | go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2(0xc00003a1f0, 0x1, 0x1)
2023-01-11T09:40:04.483Z | /go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:123 +0x257a
2023-01-11T09:40:04.483Z | go.etcd.io/etcd/server/v3/etcdmain.Main(0xc00003a1f0, 0x1, 0x1)
2023-01-11T09:40:04.483Z | /go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/main.go:40 +0x13f
2023-01-11T09:40:04.483Z | main.main()
2023-01-11T09:40:04.483Z | /go/src/go.etcd.io/etcd/release/etcd/server/main.go:32 +0x45
```

### Additional information

What can I do?

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by dforel** [comment]
i also see this issue, 
did your solve this question?
@MirtoBusico

**Comment by MirtoBusico** [comment]
Hi @dforel it was a long time ago.
I found that a lot of problem were caused by a slow hard disk containing the VM disks.
After I moved the VM disks to an NVME disk the problems disappeaded

**Comment by dforel** [comment]
> Hi @dforel it was a long time ago. I found that a lot of problem were caused by a slow hard disk containing the VM disks. After I moved the VM disks to an NVME disk the problems disappeaded

thank you，i ask my cloud server friend to try that。
