### ISSUE TITLE
[bitnami/spark] Connection issues with worker node

### ISSUE THREAD

**Issue by tgallauner** [bitnami/containers#25805]
### Name and Version

bitnami/spark:3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- Using default docker-compose.yml (https://github.com/bitnami/containers/blob/main/bitnami/spark/docker-compose.yml)
   - additional ports for master and worker are added ('7077:7077', '8081:8081')
- latest version of winutils installed (https://github.com/cdarlint/winutils)
- Python 3.10.8
- Basic python script stalls with:
   - WARN ProcfsMetricsGetter: Exception when trying to compute pagesize, as a result reporting of ProcessTree metrics is stopped
   - WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
- stderr log of worker:
```
   [...]
   Caused by: java.io.IOException: Failed to connect to host.docker.internal/192.168.65.2:30852
   [...]
   Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: host.docker.internal/192.168.65.2:30852
```

### What is the expected behavior?

using pyspark on master the following result is achieved (working):
```
    root
      |-- id: long (nullable = true)
      |-- label: string (nullable = true)

    +---+-----+                                                                     
    | id|label|
    +---+-----+
    |  1|  foo|
    |  2|  bar|
    +---+-----+

    [Row(mean=1.5)]
```

### What do you see instead?

Python script stalls with:
```
23/03/01 17:08:14 WARN ProcfsMetricsGetter: Exception when trying to compute pagesize, as a result reporting of ProcessTree metrics is stopped
23/03/01 17:08:21 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
23/03/01 17:08:36 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
23/03/01 17:08:51 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[...]
```
### Additional information

Python script for testing used:
```
    spark = SparkSession.builder \
        .master(r'spark://localhost:7077') \
        .appName('Test') \
        .getOrCreate()

    df = spark.createDataFrame(
    [
        (1, "foo"),  # create your data here, be consistent in the types.
        (2, "bar"),
    ],
    ["id", "label"]  # add your column names here
    )

    df.printSchema()
    df.show()

    df_mean = df.select(_mean(col('id')).alias('mean'))
    print(df_mean.collect())
    
    spark.stop()
```
The script runs until
```
    root
     |-- id: long (nullable = true)
     |-- label: string (nullable = true)

     [Stage 0:>                                                          (0 + 0) / 1]
```
then 
```
    23/03/01 17:16:21 WARN ProcfsMetricsGetter: Exception when trying to compute pagesize, as a result reporting of ProcessTree metrics is stopped
     23/03/01 17:16:25 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
```
Log of stderr in worker
```
    Spark Executor Command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "- 
    Xmx1024M" "-Dspark.driver.port=30852" "-XX:+IgnoreUnrecognizedVMOptions" "--add-opens=java.base/java.lang=ALL- 
    UNNAMED" "--add-opens=java.base/java.lang.invoke=ALL-UNNAMED" "--add-opens=java.base/java.lang.reflect=ALL-
    UNNAMED" "--add-opens=java.base/java.io=ALL-UNNAMED" "--add-opens=java.base/java.net=ALL-UNNAMED" "--add-
    opens=java.base/java.nio=ALL-UNNAMED" "--add-opens=java.base/java.util=ALL-UNNAMED" "--add-
    opens=java.base/java.util.concurrent=ALL-UNNAMED" "--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED" 
    "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED" "--add-opens=java.base/sun.nio.cs=ALL-UNNAMED" "--add-
    opens=java.base/sun.security.action=ALL-UNNAMED" "--add-opens=java.base/sun.util.calendar=ALL-UNNAMED" "--add-
    opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--
    driver-url" "spark://CoarseGrainedScheduler@host.docker.internal:30852" "--executor-id" "0" "--hostname" "172.19.0.2" "--
    cores" "2" "--app-id" "app-20230301155456-0000" "--worker-url" "spark://Worker@172.19.0.2:34107"

    ========================================


    Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties

    Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:427)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:416)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)

    Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:447)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:445)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	... 4 more

    Caused by: java.io.IOException: Failed to connect to host.docker.internal/192.168.65.2:30852
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

    Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 
    host.docker.internal/192.168.65.2:30852

    Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by javsalgar** [comment]
Hi,

It seesm to me that there is a networking issue in your configuration. This 192.168... set of addresses are in the same space as the host or are different? From where are you launching the script? Could you launch it in a container in the same network ?

**Comment by tgallauner** [comment]
I could find a solution: 

I had to add

    extra_hosts:
           - "host.docker.internal:<host-ip-address>"

in docker-compose.yml
    
Now it is working as expected.
Thank you for your support!

**Comment by javsalgar** [comment]
Thank you so much for sharing, the community will benefit from this! :D

**Comment by awaisajaz1** [comment]
Tried every single document to find the solution but finally solved it ;)

**Comment by simone-desantis** [comment]
In my experience some older spark images were experiencing this issue. 
Using the latest image at the moment (3.5.0) it works.

**Comment by hughesadam87** [comment]
Thanks - this saved my ASS!  Was still happening to me as of March 2024, using bitnami/spark:3.5.1.

I'm a windows user and couldn't run a pyspark script from my laptop and have it executed on the cluster running on docker-compose from this library.  

Hazy on some of this, but GPT is saying the following about DockerDeskop:

`Docker Desktop for Windows and Mac automatically injects certain DNS entries into the containers it manages to facilitate easier networking, especially for development purposes. One of these special DNS entries is host.docker.internal, which Docker Desktop resolves to the internal IP address of the host machine running Docker. This feature allows containers to communicate with services running on the host, making it simpler to set up development environments where your containerized application might need to access a database, API, or other services running locally outside of Docker.`

So unclear we're required to explicitly add the host IP (got from `ipconfig`).  For completeness, here's my entire docker-compose and python script, for anyone having this issue.

``` 
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    extra_hosts:
      - "host.docker.internal:192.168.40.245"
  spark-worker:
    image: docker.io/bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    extra_hosts:
      - "host.docker.internal:192.168.40.245"
```

```

from pyspark.sql import SparkSession


def main():
    # Initialize SparkSession
    spark = SparkSession.builder \
        .appName("HelloWorld") \
        .master("spark://localhost:7077") \
        .getOrCreate()

    # Create an RDD containing numbers from 1 to 10
    numbers_rdd = spark.sparkContext.parallelize(range(1, 11))

    # Count the elements in the RDD
    count = numbers_rdd.count()

    print(f"Count of numbers from 1 to 10 is: {count}")

    # Stop the SparkSession
    spark.stop()


if __name__ == "__main__":
    main()
```

**Comment by izzaldeen98** [comment]
@hughesadam87 Hi Man , I'm facing the same issue here tried to copy `docker-compose.yml` you mentioned up there but I'm stuck on this:

```24/04/11 03:37:29 WARN Shell: Did not find winutils.exe: java.io.FileNotFoundException: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset. -see https://wiki.apache.org/hadoop/WindowsProblems
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/04/11 03:37:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
root
 |-- Name: string (nullable = true)
 |-- Age: long (nullable = true)

[Stage 0:>                                                          (0 + 1) / 1]
```


### And this on my job UI

![image](https://github.com/bitnami/containers/assets/57918132/f7d15f0d-1fe5-4088-8c4b-08cc7ec1b1a6)

and this is the `stderr` 

```
Spark Executor Command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=54908" "-Djava.net.preferIPv6Addresses=false" "-XX:+IgnoreUnrecognizedVMOptions" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/java.lang.invoke=ALL-UNNAMED" "--add-opens=java.base/java.lang.reflect=ALL-UNNAMED" "--add-opens=java.base/java.io=ALL-UNNAMED" "--add-opens=java.base/java.net=ALL-UNNAMED" "--add-opens=java.base/java.nio=ALL-UNNAMED" "--add-opens=java.base/java.util=ALL-UNNAMED" "--add-opens=java.base/java.util.concurrent=ALL-UNNAMED" "--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED" "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED" "--add-opens=java.base/sun.nio.cs=ALL-UNNAMED" "--add-opens=java.base/sun.security.action=ALL-UNNAMED" "--add-opens=java.base/sun.util.calendar=ALL-UNNAMED" "--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED" "-Djdk.reflect.useDirectMethodHandle=false" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@host.docker.internal:54908" "--executor-id" "0" "--hostname" "172.21.0.3" "--cores" "1" "--app-id" "app-20240411004910-0000" "--worker-url" "spark://Worker@172.21.0.3:36463" "--resourceProfileId" "0"
========================================

Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
24/04/11 00:49:12 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 116@35e699bbeb6b
24/04/11 00:49:12 INFO SignalUtils: Registering signal handler for TERM
24/04/11 00:49:12 INFO SignalUtils: Registering signal handler for HUP
24/04/11 00:49:12 INFO SignalUtils: Registering signal handler for INT
24/04/11 00:49:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/04/11 00:49:12 INFO SecurityManager: Changing view acls to: spark,owner
24/04/11 00:49:12 INFO SecurityManager: Changing modify acls to: spark,owner
24/04/11 00:49:12 INFO SecurityManager: Changing view acls groups to: 
24/04/11 00:49:12 INFO SecurityManager: Changing modify acls groups to: 
24/04/11 00:49:12 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark, owner; groups with view permissions: EMPTY; users with modify permissions: spark, owner; groups with modify permissions: EMPTY
24/04/11 00:49:12 INFO TransportClientFactory: Successfully created connection to host.docker.internal/192.168.8.101:54908 after 85 ms (0 ms spent in bootstraps)
24/04/11 00:49:13 INFO SecurityManager: Changing view acls to: spark,owner
24/04/11 00:49:13 INFO SecurityManager: Changing modify acls to: spark,owner
24/04/11 00:49:13 INFO SecurityManager: Changing view acls groups to: 
24/04/11 00:49:13 INFO SecurityManager: Changing modify acls groups to: 
24/04/11 00:49:13 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark, owner; groups with view permissions: EMPTY; users with modify permissions: spark, owner; groups with modify permissions: EMPTY
24/04/11 00:49:13 INFO TransportClientFactory: Successfully created connection to host.docker.internal/192.168.8.101:54908 after 3 ms (0 ms spent in bootstraps)
24/04/11 00:49:13 INFO DiskBlockManager: Created local directory at /tmp/spark-9c6e37ce-9afa-4b5d-aa7e-c16556b75681/executor-865217fb-ed83-4809-988a-d0cd96de426a/blockmgr-20c8f8c9-8c32-4b2e-9b4c-582a1ca35105
24/04/11 00:49:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
24/04/11 00:49:13 INFO CoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@host.docker.internal:54908
24/04/11 00:49:13 INFO WorkerWatcher: Connecting to worker spark://Worker@172.21.0.3:36463
24/04/11 00:49:13 INFO TransportClientFactory: Successfully created connection to /172.21.0.3:36463 after 2 ms (0 ms spent in bootstraps)
24/04/11 00:49:13 INFO WorkerWatcher: Successfully connected to spark://Worker@172.21.0.3:36463
24/04/11 00:49:13 INFO ResourceUtils: ==============================================================
24/04/11 00:49:13 INFO ResourceUtils: No custom resources configured for spark.executor.
24/04/11 00:49:13 INFO ResourceUtils: ==============================================================
24/04/11 00:49:13 INFO CoarseGrainedExecutorBackend: Successfully registered with driver
24/04/11 00:49:13 INFO Executor: Starting executor ID 0 on host 172.21.0.3
24/04/11 00:49:13 INFO Executor: OS info Linux, 5.15.146.1-microsoft-standard-WSL2, amd64
24/04/11 00:49:13 INFO Executor: Java version 17.0.10
24/04/11 00:49:13 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40983.
24/04/11 00:49:13 INFO NettyBlockTransferService: Server created on 172.21.0.3:40983
24/04/11 00:49:13 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
24/04/11 00:49:13 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(0, 172.21.0.3, 40983, None)
24/04/11 00:49:13 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(0, 172.21.0.3, 40983, None)
24/04/11 00:49:13 INFO BlockManager: Initialized BlockManager: BlockManagerId(0, 172.21.0.3, 40983, None)
24/04/11 00:49:13 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
24/04/11 00:49:13 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@3aa38ac5 for default.
24/04/11 00:49:17 ERROR Inbox: Ignoring error
java.io.UTFDataFormatException: malformed input around byte 2269
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:649)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:558)
	at org.apache.spark.scheduler.TaskDescription$.$anonfun$decode$1(TaskDescription.scala:211)
	at org.apache.spark.scheduler.TaskDescription$.$anonfun$decode$1$adapted(TaskDescription.scala:210)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at org.apache.spark.scheduler.TaskDescription$.decode(TaskDescription.scala:210)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:192)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Please advise on this

**Comment by hughesadam87** [comment]
@izzaldeen98  is it possible the version of python you're running on the containers is different from the one you're submitting the job from (ie. from your host machine)?  Both pyspark and python versions should match as close as possible or you'll get serialization errors.  Just guess tho, may be something else

**Comment by dgrahn** [comment]
@izzaldeen98 I'm having the same issue running 3.5.1. I'm running spark with NodePort and confirmed that the python and pyspark versions were the same.

**Comment by reddimsetti-hub** [comment]
ee

**Comment by 1Edtrujillo1** [comment]
Hi, how can I solve this with docker swarm?
