### ISSUE TITLE
[bitnami/zookeeper] How to config without docker network cluster ???

### ISSUE THREAD

**Issue by isfong** [bitnami/containers#27173]
### Name and Version

bitnami/zookeeper:3.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`Bitnami`
```yaml
version: '3'
services:

  zookeeper-1:
    image: bitnami/zookeeper:3.8
    ports:
      - '2181:2181'
      - '20001:2888'
      - '30001:3888'
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=${DOCKER_HOST_IP}:20001:30001,${DOCKER_HOST_IP}:20002:30002,${DOCKER_HOST_IP}:20003:30003
  zookeeper-2:
    image: bitnami/zookeeper:3.8
    ports:
      - '2182:2181'
      - '20002:2888'
      - '30002:3888'
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=${DOCKER_HOST_IP}:20001:30001,${DOCKER_HOST_IP}:20002:30002,${DOCKER_HOST_IP}:20003:30003
  zookeeper-3:
    image: bitnami/zookeeper:3.8
    ports:
      - '2183:2181'
      - '20003:2888'
      - '30003:3888'
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=${DOCKER_HOST_IP}:20001:30001,${DOCKER_HOST_IP}:20002:30002,${DOCKER_HOST_IP}:20003:30003
```
```java
2023-03-13 03:12:56,081 [myid:] - ERROR [ListenerHandler-/192.168.0.200:30001:o.a.z.s.q.QuorumCnxManager$Listener$ListenerHandler@1099] - Exception while listening to address /192.168.0.200:30001
2023-03-13T03:12:56.082236700Z java.net.BindException: Cannot assign requested address (Bind failed)
2023-03-13T03:12:56.082257971Z 	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
2023-03-13T03:12:56.082263187Z 	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:452)
2023-03-13T03:12:56.082265973Z 	at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
2023-03-13T03:12:56.082268097Z 	at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
2023-03-13T03:12:56.082270221Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.createNewServerSocket(QuorumCnxManager.java:1141)
2023-03-13T03:12:56.082272605Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.acceptConnections(QuorumCnxManager.java:1070)
2023-03-13T03:12:56.082279764Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.run(QuorumCnxManager.java:1039)
2023-03-13T03:12:56.082286285Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2023-03-13T03:12:56.082297032Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-03-13T03:12:56.082304528Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-03-13T03:12:56.082307840Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-03-13T03:12:56.082314775Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-13T03:12:56.469366708Z 2023-03-13 03:12:56,468 [myid:] - INFO  [QuorumPeer[myid=1](plain=0.0.0.0:2181)(secure=disabled):o.a.z.s.q.FastLeaderElection@996] - Notification time out: 25600 ms
2023-03-13T03:12:56.470024359Z 2023-03-13 03:12:56,469 [myid:] - WARN  [QuorumConnectionThread-[myid=1]-3:o.a.z.s.q.QuorumCnxManager@401] - Cannot open channel to 3 at election address /192.168.0.200:30003
2023-03-13T03:12:56.470461194Z java.net.ConnectException: Connection refused (Connection refused)
2023-03-13T03:12:56.470480970Z 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
2023-03-13T03:12:56.470491135Z 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
2023-03-13T03:12:56.470498879Z 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
2023-03-13T03:12:56.470501764Z 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
2023-03-13T03:12:56.470507069Z 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2023-03-13T03:12:56.470511591Z 	at java.base/java.net.Socket.connect(Socket.java:609)
2023-03-13T03:12:56.470517325Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:384)
2023-03-13T03:12:56.470522019Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:458)
2023-03-13T03:12:56.470524739Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-03-13T03:12:56.470526976Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-03-13T03:12:56.470529176Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-13T03:12:56.470531319Z 2023-03-13 03:12:56,469 [myid:] - WARN  [QuorumConnectionThread-[myid=1]-2:o.a.z.s.q.QuorumCnxManager@401] - Cannot open channel to 2 at election address /192.168.0.200:30002
2023-03-13T03:12:56.470533537Z java.net.ConnectException: Connection refused (Connection refused)
2023-03-13T03:12:56.470540509Z 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
2023-03-13T03:12:56.470543980Z 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
2023-03-13T03:12:56.470546423Z 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
2023-03-13T03:12:56.470548765Z 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
2023-03-13T03:12:56.470550880Z 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2023-03-13T03:12:56.470552993Z 	at java.base/java.net.Socket.connect(Socket.java:609)
2023-03-13T03:12:56.470555060Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:384)
2023-03-13T03:12:56.470562298Z 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:458)
2023-03-13T03:12:56.470566890Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-03-13T03:12:56.470573265Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-03-13T03:12:56.470577528Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

### What do you see instead?

Can't  create a cluster

**Comment by javsalgar** [comment]
Hi,

The issue I see is that you are binding the same external port, and therefore it is failing. Could you explain your use case in more detail?

**Comment by isfong** [comment]
> 你好，
> 
> 我看到的问题是你绑定了相同的外部端口，因此它丢失了。你能更详细地解释你的用例吗？

I don't think it's a matter of binding the same external port, zk requires the container's native private `IP:PORT`, not the non-container's private IP `$DOCKER_HOST_IP`

**Comment by isfong** [comment]
> Hi,
> 
> The issue I see is that you are binding the same external port, and therefore it is failing. Could you explain your use case in more detail?

I don't think it's a matter of binding the same external port, zk requires the container's native private `IP:PORT`, not the non-container's private IP `$DOCKER_HOST_IP`.
Can you fix my `docker-composite` file? Cheers!

**Comment by javsalgar** [comment]
I'm not sure if I understand the question. You mention that you need the native private network but the title of the issue is to not use docker networking. Did you check this docker-compose file? https://github.com/bitnami/containers/blob/main/bitnami/zookeeper/docker-compose-cluster.yml
