### ISSUE TITLE
[bitnami/matomo] ERROR: for matomo  a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by yannours** [bitnami/containers#27826]
### Name and Version

bitnami/matomo:4.14.0

### What architecture are you using?

None

### What steps will reproduce the bug?

```
$> docker pull bitnami/matomo
$> curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/matomo/docker-compose.yml > docker-compose.yml
$> docker-compose up -d
```

### What is the expected behavior?

It should populate two running docker container:
```
- matomo_mariadb_1
- matomo_matomo_1
```

### What do you see instead?

I have an error:
```
$> docker-compose up -d
Creating network "matomo_default" with the default driver
Creating volume "matomo_mariadb_data" with local driver
Creating volume "matomo_matomo_data" with local driver
Pulling mariadb (docker.io/bitnami/mariadb:10.6)...
10.6: Pulling from bitnami/mariadb
3399acfa60e3: Pull complete
Digest: sha256:15edb5643b738b80ba6829150b78181512ba0e3fee4831e39007decdf8e45595
Status: Downloaded newer image for bitnami/mariadb:10.6
Pulling matomo (docker.io/bitnami/matomo:4)...
4: Pulling from bitnami/matomo
Digest: sha256:6d041d766fc1959796c6f765bd607535b6de34cd82695bf2dce2d7aeecb480f8
Status: Downloaded newer image for bitnami/matomo:4
Creating matomo_mariadb_1 ... done
Creating matomo_matomo_1  ... 

ERROR: for matomo_matomo_1  a bytes-like object is required, not 'str'

ERROR: for matomo  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/784dea453cfe19740d47ed13a6470d2addb556a74faf74acc2f84b8caa43c7e1/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint matomo_matomo_1 (4d76f7cf22fb7702284c07590f39e1754849781aa2d63be02fbc5fb296c17a8f): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 545, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 460, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 465, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 457, in create_and_start
    self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
```

And I have only one running docker container:
```
$> docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS      NAMES
2d70f4e671f8   bitnami/mariadb:10.6   "/opt/bitnami/script…"   6 minutes ago   Up 6 minutes   3306/tcp   matomo_mariadb_1
```

### Additional information

```
$> cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
```
$> docker -v
Docker version 23.0.1, build a5ee5b1
```

**Comment by javsalgar** [comment]
Hi,

We were unable to reproduce the issue

```
» curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/matomo/docker-compose.yml > docker-compose.yml

/tmp
» docker-compose up
[+] Running 4/4
 ⠿ mariadb Pulled                                                                                                                43.6s
   ⠿ 3399acfa60e3 Pull complete                                                                                                  40.0s
 ⠿ matomo Pulled                                                                                                                 65.4s
   ⠿ 701b1dee85c2 Pull complete                                                                                                  61.7s
[+] Running 5/5
 ⠿ Network tmp_default        Created                                                                                             0.2s
 ⠿ Volume "tmp_matomo_data"   Created                                                                                             0.0s
 ⠿ Volume "tmp_mariadb_data"  Created                                                                                             0.0s
 ⠿ Container tmp-mariadb-1    Created                                                                                             2.7s
 ⠿ Container tmp-matomo-1     Created                                                                                             0.1s
Attaching to tmp-mariadb-1, tmp-matomo-1
tmp-mariadb-1  | mariadb 08:19:32.74
tmp-mariadb-1  | mariadb 08:19:32.74 Welcome to the Bitnami mariadb container
tmp-mariadb-1  | mariadb 08:19:32.74 Subscribe to project updates by watching https://github.com/bitnami/containers
tmp-mariadb-1  | mariadb 08:19:32.74 Submit issues and feature requests at https://github.com/bitnami/containers/issues
tmp-mariadb-1  | mariadb 08:19:32.75
tmp-mariadb-1  | mariadb 08:19:32.75 INFO  ==> ** Starting MariaDB setup **
tmp-mariadb-1  | mariadb 08:19:32.78 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
tmp-mariadb-1  | mariadb 08:19:32.78 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
tmp-mariadb-1  | mariadb 08:19:32.79 INFO  ==> Initializing mariadb database
tmp-mariadb-1  | mariadb 08:19:32.81 INFO  ==> Updating 'my.cnf' with custom configuration
tmp-mariadb-1  | mariadb 08:19:32.81 INFO  ==> Setting user option
tmp-mariadb-1  | mariadb 08:19:32.84 INFO  ==> Setting slow_query_log option
tmp-mariadb-1  | mariadb 08:19:32.89 INFO  ==> Setting long_query_time option
tmp-mariadb-1  | mariadb 08:19:32.92 INFO  ==> Installing database
tmp-matomo-1   | matomo 08:19:33.49
tmp-matomo-1   | matomo 08:19:33.49 Welcome to the Bitnami matomo container
tmp-matomo-1   | matomo 08:19:33.50 Subscribe to project updates by watching https://github.com/bitnami/containers
tmp-matomo-1   | matomo 08:19:33.50 Submit issues and feature requests at https://github.com/bitnami/containers/issues
tmp-matomo-1   | matomo 08:19:33.50
tmp-matomo-1   | matomo 08:19:33.50 INFO  ==> ** Starting Matomo setup **
tmp-matomo-1   | realpath: /bitnami/apache/conf: No such file or directory
tmp-matomo-1   | matomo 08:19:33.54 INFO  ==> Configuring Apache ServerTokens directive
tmp-matomo-1   | matomo 08:19:33.56 INFO  ==> Configuring PHP options
tmp-matomo-1   | matomo 08:19:33.57 INFO  ==> Setting PHP expose_php option
tmp-matomo-1   | matomo 08:19:33.59 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
tmp-matomo-1   | matomo 08:19:33.63 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
tmp-matomo-1   | matomo 08:19:33.72 INFO  ==> Ensuring Matomo directories exist
tmp-matomo-1   | matomo 08:19:33.73 INFO  ==> Trying to connect to the database server
tmp-mariadb-1  | mariadb 08:19:34.50 INFO  ==> Starting mariadb in background
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 120
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Number of pools: 1
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Using Linux native AIO
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Completed initialization of buffer pool
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: 128 rollback segments are active.
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Creating shared tablespace for temporary tables
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: 10.6.12 started; log sequence number 42120; transaction id 14
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] Plugin 'FEEDBACK' is disabled.
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] InnoDB: Buffer pool(s) load completed at 230321  8:19:34
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] Server socket created on IP: '127.0.0.1'.
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Warning] 'user' entry 'root@8807bc5b449d' ignored in --skip-name-resolve mode.
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Warning] 'user' entry '@8807bc5b449d' ignored in --skip-name-resolve mode.
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Warning] 'proxies_priv' entry '@% root@8807bc5b449d' ignored in --skip-name-resolve mode.
tmp-mariadb-1  | 2023-03-21  8:19:34 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
tmp-mariadb-1  | Version: '10.6.12-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
tmp-mariadb-1  | mariadb 08:19:36.52 INFO  ==> Configuring authentication
tmp-mariadb-1  | 2023-03-21  8:19:36 5 [Warning] 'proxies_priv' entry '@% root@8807bc5b449d' ignored in --skip-name-resolve mode.
tmp-mariadb-1  | mariadb 08:19:36.67 INFO  ==> Running mysql_upgrade
tmp-mariadb-1  | find: '/docker-entrypoint-startdb.d/': No such file or directory
tmp-mariadb-1  | mariadb 08:19:36.74 INFO  ==> Stopping mariadb
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] InnoDB: FTS optimize thread exiting.
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] InnoDB: Starting shutdown...
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] InnoDB: Dumping buffer pool(s) to /bitnami/mariadb/data/ib_buffer_pool
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] InnoDB: Buffer pool(s) dump completed at 230321  8:19:36
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] InnoDB: Shutdown completed; log sequence number 42132; transaction id 15
tmp-mariadb-1  | 2023-03-21  8:19:36 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
tmp-mariadb-1  |
tmp-mariadb-1  |
tmp-mariadb-1  | mariadb 08:19:37.78 INFO  ==> ** MariaDB setup finished! **
tmp-mariadb-1  | mariadb 08:19:37.82 INFO  ==> ** Starting MariaDB **
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 1
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Number of pools: 1
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Using Linux native AIO
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Completed initialization of buffer pool
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: 128 rollback segments are active.
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Creating shared tablespace for temporary tables
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: 10.6.12 started; log sequence number 42132; transaction id 14
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
tmp-mariadb-1  | 2023-03-21  8:19:37 0 [Note] Plugin 'FEEDBACK' is disabled.
tmp-mariadb-1  | 2023-03-21  8:19:38 0 [Note] InnoDB: Buffer pool(s) load completed at 230321  8:19:38
tmp-mariadb-1  | 2023-03-21  8:19:38 0 [Note] Server socket created on IP: '0.0.0.0'.
tmp-mariadb-1  | 2023-03-21  8:19:38 0 [Warning] 'proxies_priv' entry '@% root@8807bc5b449d' ignored in --skip-name-resolve mode.
tmp-mariadb-1  | 2023-03-21  8:19:38 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
tmp-mariadb-1  | Version: '10.6.12-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
tmp-matomo-1   | matomo 08:19:38.80 INFO  ==> Starting apache in background
tmp-matomo-1   | [Tue Mar 21 08:19:38.912041 2023] [ssl:warn] [pid 87] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
tmp-matomo-1   | [Tue Mar 21 08:19:38.912594 2023] [ssl:warn] [pid 87] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
tmp-matomo-1   | matomo 08:19:43.95 INFO  ==> apache started
tmp-matomo-1   | matomo 08:19:43.95 INFO  ==> Passing Matomo installation wizard
tmp-matomo-1   | matomo 08:19:56.38 INFO  ==> Matomo wizard finished successfully
tmp-matomo-1   | matomo 08:19:56.38 INFO  ==> Stopping apache
tmp-matomo-1   | matomo 08:19:57.42 INFO  ==> apache stopped
tmp-matomo-1   | matomo 08:19:57.43 INFO  ==> Persisting Matomo installation
tmp-matomo-1   | matomo 08:19:59.73 WARN  ==> Skipping cron configuration for Matomo because of running as a non-root user
tmp-matomo-1   |
tmp-matomo-1   | matomo 08:19:59.73 INFO  ==> ** Matomo setup finished! **
tmp-matomo-1   | matomo 08:19:59.74 WARN  ==> Cron will not be started because of running as a non-root user
tmp-matomo-1   | matomo 08:19:59.76 INFO  ==> ** Starting Apache **
tmp-matomo-1   | [Tue Mar 21 08:19:59.813121 2023] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
tmp-matomo-1   | [Tue Mar 21 08:19:59.813556 2023] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
tmp-matomo-1   | [Tue Mar 21 08:19:59.852383 2023] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
tmp-matomo-1   | [Tue Mar 21 08:19:59.853062 2023] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
tmp-matomo-1   | [Tue Mar 21 08:19:59.883426 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.56 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
tmp-matomo-1   | [Tue Mar 21 08:19:59.883505 2023] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

It seems to be an issue in the Docker daemon rather than the Bitnami container. Could you try in another machine?

**Comment by yannours** [comment]
Ok so I've created a from scratch ubuntu 22.04 server and install SSH, docker, and docker-compose.  
Pulled the bitnami/matomo latest and run docker compose and it works perfectly.  
So my problem is environmental and on my side, ty for the help.
