### ISSUE TITLE
[bitnami/kafka] KRaft should not be enabled silently

### ISSUE THREAD

**Issue by vincentbernat** [bitnami/containers#31488]
### Name and Version

bitnami/kafka:3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Upgrade to a recent version of the image
2. Information in zookeeper are lost

### What is the expected behavior?

Upgrading to the same minor version should not break existing metadata.

### What do you see instead?

Metadata not fetched from Zookeeper anymore.

### Additional information

This was broken by #31435.

**Comment by retzkek** [comment]
For the record this happened in 3.2 as well: https://github.com/bitnami/containers/pull/31434

**Comment by rpulijala** [comment]
Our kafka is failing with the below error, we were planning for KRaft upgrade in the next couple of months on our own time, but this has broke our environments

```
kafka 16:01:46.99 
kafka 16:01:46.99 Welcome to the Bitnami kafka container
kafka 16:01:46.99 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 16:01:46.99 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 16:01:46.99 
kafka 16:01:47.00 INFO  ==> ** Starting Kafka setup **
kafka 16:01:47.06 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka 16:01:47.06 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
kafka 16:01:47.07 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 16:01:47.08 INFO  ==> Initializing Kafka...
kafka 16:01:47.09 INFO  ==> No injected configuration files found, creating default config files
kafka 16:01:47.23 INFO  ==> Initializing KRaft...
kafka 16:01:47.23 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka 16:01:48.54 INFO  ==> Generated Kafka cluster ID '1iD2ra0dQT2TQzeeOaH4LA'
kafka 16:01:48.55 INFO  ==> Formatting storage directories to add metadata...
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: controller.listener.names must contain at least one value appearing in the 'listeners' configuration when running the KRaft controller role
    at scala.Predef$.require(Predef.scala:281)
    at kafka.server.KafkaConfig.validateControllerListenerExistsForKRaftController$1(KafkaConfig.scala:2122)
    at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2184)
    at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2063)
    at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1494)
    at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
    at scala.Option.flatMap(Option.scala:271)
    at kafka.tools.StorageTool$.main(StorageTool.scala:41)
    at kafka.tools.StorageTool.main(StorageTool.scala)
```

is it possible to undo this for `3.3.2` ?

**Comment by vincentbernat** [comment]
Also, setting `KAFKA_ENABLE_KRAFT` to `no` will trigger an error when using `ALLOW_PLAINTEXT_LISTENER` to `yes` as there is no security protocol defined for listener CONTROLLER:

```
[2023-04-28 16:22:51,051] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.lang.IllegalArgumentException: Error creating broker listeners from 'PLAINTEXT://:9092,CONTROLLER://:9093': No security protocol defined for listener CONTROLLER
        at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:273)
        at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:252)
        at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:1956)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1694)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1495)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1418)
        at kafka.Kafka$.buildServer(Kafka.scala:67)
        at kafka.Kafka$.main(Kafka.scala:87)
        at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener CONTROLLER
        at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:49)
        at scala.collection.immutable.Map$Map4.getOrElse(Map.scala:450)
        at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:49)
        at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:54)
        at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:270)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:270)
        ... 8 more
```

**Comment by OneCricketeer** [comment]
> `KAFKA_ENABLE_KRAFT` to no will trigger an error as there is no security protocol defined for listener CONTROLLER

Same here. This is definitely a bug since `CONTROLLER` should never be parsed from the `listeners`. 

You can workaround this by adding

```yaml
KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,...(your other mappings)
```

**Comment by corico44** [comment]
Hello,

In order to continue using Zookeeper, the necessary variables must be correctly set as indicated in the documentation: https://github.com/bitnami/containers/tree/main/bitnami/kafka#kafka-with-zookeeper.
In this case, the following variables would be needed:
```
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
```

**Comment by ujhazib** [comment]
I also had a quite lengthy headscratch recently, because I couldn't believe a patch update will break anything in my setup. I was using bitnami/kafka:3.3

**Comment by jotamartos** [comment]
Hi @ujhazib, 

[Using rolling tags in a production deployment is not a good practice](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/). As you may know, we follow the same versioning than the upstream package and, changes are being introduced regularly either because of a user's contribution or a bug fix on our side. If you take a look at our charts, we also stick to a fixed release, not a rolling tag, to avoid issues when upgrading the deployment. Charts allow us create a new major version but that's not something we can do in containers and that's why we document the major changes in the README file.

https://github.com/bitnami/containers/tree/main/bitnami/kafka#notable-changes

As you can see there, there have been many changes during the lifetime of the container so we suggest you take a look at that list when upgrading the container in the future. If you plan the upgrade in advance, you shouldn't have problems when using our solutions 

Thanks

**Comment by ujhazib** [comment]
@jotamartos there is a reason why we used partial version matching (and ignoring patch version), but if I would have said something like we depended on 3.3.2, which I think also worked differently before, does it mean that Bitnami should change the internal configuration setting in a way that there are breaking changes? On patch level? Well my mistake as well that I thought that big changes in how bitnami creates scripts around the kafka image will be changed significantly in bigger version updates, because you are not binded to kafka's versioning directly. But then the version naming of these images are also conceptually also broken. You should somehow represent this in the versions, unlike in other bitnami images, where a packaged infrastructure is truly almost just an underlying debian and a few env vars.
Plus bumping this thread, I think @OneCricketeer had the best point of all in this conversation.
