### ISSUE TITLE
[bitnami/kafka] Apply security for Kafka

### ISSUE THREAD

**Issue by MyungChi** [bitnami/containers#32285]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I apply SSL into kafka, I got error as below. I don't know what was wrong ?
```
# docker-compose logs kafka
Attaching to kafka
kafka            | kafka 00:03:02.37
kafka            | kafka 00:03:02.38 Welcome to the Bitnami kafka container
kafka            | kafka 00:03:02.38 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka            | kafka 00:03:02.38 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka            | kafka 00:03:02.39
kafka            | kafka 00:03:02.39 INFO  ==> ** Starting Kafka setup **
kafka            | kafka 00:03:02.47 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka            | kafka 00:03:02.50 INFO  ==> Initializing Kafka...
kafka            | kafka 00:03:02.51 INFO  ==> No injected configuration files found, creating default config files
kafka            | kafka 00:03:02.70 INFO  ==> Initializing KRaft...
kafka            | kafka 00:03:02.71 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka            | kafka 00:03:04.15 INFO  ==> Generated Kafka cluster ID 'BYIdcxs3Tauog38mWj9D1A'
kafka            | kafka 00:03:04.16 INFO  ==> Formatting storage directories to add metadata...
kafka            | Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: inter.broker.listener.name must be a listener name defined in advertised.listeners. The valid options based on currently configured listeners are SASL_SSL
kafka            |      at scala.Predef$.require(Predef.scala:281)
kafka            |      at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2264)
kafka            |      at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2107)
kafka            |      at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1533)
kafka            |      at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
kafka            |      at scala.Option.flatMap(Option.scala:271)
kafka            |      at kafka.tools.StorageTool$.main(StorageTool.scala:41)
kafka            |      at kafka.tools.StorageTool.main(StorageTool.scala)


1. cat docker-compose.yml

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - my-network
    ports:
      - "9092:9092"
    volumes:
      - "/DATA/kafka-data:/bitnami"
      - "/DATA/myapp/cert/kafka/smartapigw.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "/DATA/myapp/cert/kafka/smartapigw.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_CERTIFICATE_PASSWORD="password!23"
      - KAFKA_TLS_TYPE=JKS # or PEM

3. run
$ docker-compose up -d

### What is the expected behavior?

_No response_

### What do you see instead?

kafka            | Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: inter.broker.listener.name must be a listener name defined in advertised.listeners. The valid options based on currently configured listeners are SASL_SSL
kafka            |      at scala.Predef$.require(Predef.scala:281)
kafka            |      at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2264)
kafka            |      at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2107)
kafka            |      at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1533)
kafka            |      at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
kafka            |      at scala.Option.flatMap(Option.scala:271)
kafka            |      at kafka.tools.StorageTool$.main(StorageTool.scala:41)
kafka            |      at kafka.tools.StorageTool.main(StorageTool.scala)
```

**Comment by OneCricketeer** [comment]
Have you tried setting the `KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL`, as the error says?

**Comment by MyungChi** [comment]
I recreate self-signed certification with CN=localhost.
Then, I succeed configuration as below. 

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    hostname: kafka.server.com
    ports:
      - "9092:9092"
    volumes:
      - "<my data volume>:/bitnami"
      - "<my server path>/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "<my server path>/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
    environment:
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,CONTROLLER://localhost:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,INTERNAL:SSL
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/ssl/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=<password>
      - KAFKA_CFG_SSL_KEY_PASSWORD=<password>
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/ssl/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=<password>
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_TLS_CLIENT_AUTH=none
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

**Comment by emeraldhieu** [comment]
I've followed the [documentation](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#security) and got the same error as the original poster. 

This doesn't work
```yml
KAFKA_CFG_LISTENERS: "SASL_SSL://:9092,CONTROLLER://:9093"
KAFKA_CFG_ADVERTISED_LISTENERS: "SASL_SSL://:9092"
KAFKA_CLIENT_USERS: user
KAFKA_CLIENT_PASSWORDS: password
KAFKA_CERTIFICATE_PASSWORD: haveaniceday
KAFKA_TLS_TYPE: JKS
```

Error
```sh
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: inter.broker.listener.name must be a listener name defined in advertised.listeners. The valid options based on currently configured listeners are SASL_SSL
```

I think the [documentation](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#security) at needs updating.

Thanks for the idea, MyungChi . Only this works for me.

```yml
KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:SSL,CONTROLLER:SSL"
KAFKA_CFG_SSL_KEYSTORE_LOCATION: "/opt/bitnami/kafka/config/certs/kafka.keystore.jks"
KAFKA_CFG_SSL_KEYSTORE_PASSWORD: haveaniceday
KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: "/opt/bitnami/kafka/config/certs/kafka.truststore.jks"
KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: haveaniceday
KAFKA_TLS_CLIENT_AUTH: none
```

---
One side note: The empty `KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM` and `hostname` don't work for me. As I understand, setting `KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM` should ignore whatever `hostname` and the "first and last names" from the prompt.
The logs constantly show

```
Caused by: java.security.cert.CertificateException: No name matching kafka-0 found
```

where `kafka-0` is my kafka service name

Solution: I have to use the Kafka service in the docker compose when prompted the "first name and last name" as guided in the docs.
