### ISSUE TITLE
[bitnami/jupyterhub] PermissionError: [Errno 13] Permission denied: '/jupyterhub_cookie_secret'

### ISSUE THREAD

**Issue by AriesT** [bitnami/containers#32650]
### Name and Version

 bitnami/jupyterhub:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

After first start

### What do you see instead?
```
[I 2023-05-04 12:36:29.008 JupyterHub app:2810] Running JupyterHub version 3.1.1
[I 2023-05-04 12:36:29.009 JupyterHub app:2840] Using Authenticator: jupyterhub.auth.PAMAuthenticator-3.1.1
[I 2023-05-04 12:36:29.009 JupyterHub app:2840] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-3.1.1
[I 2023-05-04 12:36:29.009 JupyterHub app:2840] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-3.1.1
[I 2023-05-04 12:36:29.034 JupyterHub app:1694] Writing cookie_secret to /jupyterhub_cookie_secret
[E 2023-05-04 12:36:29.034 JupyterHub app:3334]
    Traceback (most recent call last):
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 3331, in launch_instance_async
        await self.initialize(argv)
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 2850, in initialize
        self.init_secrets()
      File "/opt/bitnami/miniconda/lib/python3.8/site-packages/jupyterhub/app.py", line 1696, in init_secrets
        with open(secret_file, 'w') as f:
    PermissionError: [Errno 13] Permission denied: '/jupyterhub_cookie_secret'
```

**Comment by javsalgar** [comment]
Hi,

How are you launching the jupyterhub container?

**Comment by lovejunvip** [comment]
I also get an error when using docker-compose.
```
services:
  JupyterHub:
    image: bitnamilegacy/jupyterhub:5.3.0-debian-12-r16
    restart: unless-stopped
    ports:
      - "18000:8000"
    environment:
      - JUPYTERHUB_USERNAME=admin
      - JUPYTERHUB_PASSWORD=bitnami
    networks:
      - default
    volumes:
      - ./jupyterhub:/opt/bitnami/jupyterhub
networks:
  default:
```
```
root@ubuntu24-server:/opt/modules/JupyterHub# docker-compose up
[+] Running 1/1
 ✔ Container jupyterhub-JupyterHub-1  Recreated                                                                          0.2s 
Attaching to JupyterHub-1
JupyterHub-1  | [I 2025-10-15 10:01:32.736 JupyterHub app:3354] Running JupyterHub version 5.3.0
JupyterHub-1  | [I 2025-10-15 10:01:32.737 JupyterHub app:3384] Using Authenticator: jupyterhub.auth.PAMAuthenticator-5.3.0
JupyterHub-1  | [I 2025-10-15 10:01:32.737 JupyterHub app:3384] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-5.3.0
JupyterHub-1  | [I 2025-10-15 10:01:32.737 JupyterHub app:3384] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-5.3.0
JupyterHub-1  | /opt/bitnami/miniforge/lib/python3.12/site-packages/jupyter_events/schema.py:68: JupyterEventsVersionWarning: The `version` property of an event schema must be a string. It has been type coerced, but in a future version of this library, it will fail to validate. Please update schema: https://schema.jupyter.org/jupyterhub/events/server-action
JupyterHub-1  |   validate_schema(_schema)
JupyterHub-1  | [I 2025-10-15 10:01:32.773 JupyterHub app:1880] Writing cookie_secret to /jupyterhub_cookie_secret
JupyterHub-1  | [E 2025-10-15 10:01:32.774 JupyterHub app:3920]
JupyterHub-1  |     Traceback (most recent call last):
JupyterHub-1  |       File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/app.py", line 3917, in launch_instance_async
JupyterHub-1  |         await self.initialize(argv)
JupyterHub-1  |       File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/app.py", line 3394, in initialize
JupyterHub-1  |         self.init_secrets()
JupyterHub-1  |       File "/opt/bitnami/miniforge/lib/python3.12/site-packages/jupyterhub/app.py", line 1882, in init_secrets
JupyterHub-1  |         with open(secret_file, 'w') as f:
JupyterHub-1  |              ^^^^^^^^^^^^^^^^^^^^^^
JupyterHub-1  |     PermissionError: [Errno 13] Permission denied: '/jupyterhub_cookie_secret'
JupyterHub-1  |     
JupyterHub-1 exited with code 0
```
