### ISSUE TITLE
our_kafka_kafka-0_1 exited with code 1

### ISSUE THREAD

**Issue by gx303841541** [bitnami/containers#32673]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?
docker-compose.yml

```yaml
version: "3"

services:
  zookeeper-0:
    image: bitnami/zookeeper:latest
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=admin
      - ZOO_SERVER_PASSWORDS=123456
      - ZOO_CLIENT_USER=admin
      - ZOO_CLIENT_PASSWORD=123456

  kafka-0:
    image: bitnami/kafka:latest
    restart: always
    hostname: kafka-0
    ports:
      - 9098:9098
      - 9099:9099
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config.properties:/opt/bitnami/kafka/config/config.properties:ro
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=admin
      - KAFKA_ZOOKEEPER_PASSWORD=123456
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=72000

      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-256

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_LISTENERS=INTERNAL://:9098,CLIENT://:9099
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-0:9098,CLIENT://kafka-0:9099
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

      - KAFKA_CERTIFICATE_PASSWORD=123456
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=123456
      - KAFKA_INTER_BROKER_USER=user
      - KAFKA_INTER_BROKER_PASSWORD=123456

      # Configure ACL
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer
      - KAFKA_CFG_SUPER_USERS=User:user

    depends_on:
      - zookeeper-0
```

### What is the expected behavior?

kafka can work

### What do you see instead?

our_kafka_kafka-0_1 exited with code 1

### Additional information
```
kafka-0_1      | kafka 06:46:41.40 Welcome to the Bitnami kafka container
kafka-0_1      | kafka 06:46:41.40 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka-0_1      | kafka 06:46:41.41 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka-0_1      | kafka 06:46:41.41
kafka-0_1      | kafka 06:46:41.42 INFO  ==> ** Starting Kafka setup **
kafka-0_1      | kafka 06:46:41.53 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
kafka-0_1      | kafka 06:46:41.58 INFO  ==> Initializing Kafka...
kafka-0_1      | kafka 06:46:41.59 INFO  ==> No injected configuration files found, creating default config files
kafka-0_1      | kafka 06:46:42.00 INFO  ==> Configuring Kafka for inter-broker communications with SASL_PLAINTEXT authentication.
kafka-0_1      | kafka 06:46:42.02 INFO  ==> Configuring Kafka for client communications with SASL_PLAINTEXT authentication.
kafka-0_1      | kafka 06:46:42.05 INFO  ==> Custom JAAS authentication file detected. Skipping generation.
kafka-0_1      | kafka 06:46:42.06 WARN  ==> The following environment variables will be ignored: KAFKA_CLIENT_USERS, KAFKA_CLIENT_PASSWORDS, KAFKA_INTER_BROKER_USER, KAFKA_INTER_BROKER_PASSWORD, KAFKA_ZOOKEEPER_USER and KAFKA_ZOOKEEPER_PASSWORD
kafka-0_1      | kafka 06:46:42.06 INFO  ==> Creating users in Zookeeper
```

**Comment by carrodher** [comment]
Could you try adding the `BITNAMI_DEBUG` env. variable to the Kafka container? In this way, there is more info in the logs during the Kafka initialization

**Comment by ztolley** [comment]
Same issue

```
services:
  zookeeper:
    image: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_KAFKA://kafka:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_KAFKA://kafka:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_KAFKA:PLAINTEXT
      - BITNAMI_DEBUG=TRUE
```

produces:

```
2023-05-05 12:10:06 kafka 11:10:06.53 
2023-05-05 12:10:06 kafka 11:10:06.53 Welcome to the Bitnami kafka container
2023-05-05 12:10:06 kafka 11:10:06.53 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-05-05 12:10:06 kafka 11:10:06.53 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-05-05 12:10:06 kafka 11:10:06.53 
2023-05-05 12:10:06 kafka 11:10:06.54 INFO  ==> ** Starting Kafka setup **
2023-05-05 12:10:06 kafka 11:10:06.56 DEBUG ==> Validating settings in KAFKA_* env vars...
2023-05-05 12:10:06 kafka 11:10:06.56 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
2023-05-05 12:10:06 kafka 11:10:06.57 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
2023-05-05 12:10:06 kafka 11:10:06.57 INFO  ==> Initializing Kafka...
2023-05-05 12:10:06 kafka 11:10:06.57 INFO  ==> No injected configuration files found, creating default config files
2023-05-05 12:10:06 kafka 11:10:06.64 INFO  ==> Initializing KRaft...
2023-05-05 12:10:06 kafka 11:10:06.65 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
2023-05-05 12:10:07 kafka 11:10:07.46 INFO  ==> Generated Kafka cluster ID 'v-lCETAvREeL4w0oFwKS3g'
2023-05-05 12:10:07 kafka 11:10:07.46 INFO  ==> Formatting storage directories to add metadata...
2023-05-05 12:10:08 Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: controller.listener.names must contain at least one value appearing in the 'listeners' configuration when running the KRaft controller role
2023-05-05 12:10:08     at scala.Predef$.require(Predef.scala:281)
2023-05-05 12:10:08     at kafka.server.KafkaConfig.validateControllerListenerExistsForKRaftController$1(KafkaConfig.scala:2176)
2023-05-05 12:10:08     at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2238)
2023-05-05 12:10:08     at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2107)
2023-05-05 12:10:08     at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1533)
2023-05-05 12:10:08     at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
2023-05-05 12:10:08     at scala.Option.flatMap(Option.scala:271)
2023-05-05 12:10:08     at kafka.tools.StorageTool$.main(StorageTool.scala:41)
2023-05-05 12:10:08     at kafka.tools.StorageTool.main(StorageTool.scala)
```

**Comment by OneCricketeer** [comment]
The latest image uses Kraft mode by default now, and is a breaking change. Refer the image README how to revert to using old Zookeeper mode

**Comment by ELMAALMI** [comment]
I solved this problem by adding 'KAFKA_ENABLE_KRAFT=no' to the environment.

**Comment by afzdev13** [comment]
> I solved this problem by adding 'KAFKA_ENABLE_KRAFT=no' to the environment.

Worked for me
