### ISSUE TITLE
pkg_resources.DistributionNotFound when activating POS module of bitnami/odoo

### ISSUE THREAD

**Issue by Yericus** [bitnami/containers#33336]
### Name and Version

bitnami/odoo

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. I installed docker on raspbian 64
2.  Installed portainer then installed bitnami/odoo through stack using the provided YAML file
3.  Installation goes ok.
4. upon login, Activate Point of Sales module.
5. Bitnami/odoo docker container goes through activation and exits with :
```
Traceback (most recent call last):
  File "/opt/bitnami/odoo/bin/odoo", line 4, in <module>
    __import__('pkg_resources').run_script('odoo==16.0.post20230415', 'odoo')
  File "/opt/bitnami/python/lib/python3.10/site-packages/setuptools-63.4.3-py3.10.egg/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/opt/bitnami/python/lib/python3.10/site-packages/setuptools-63.4.3-py3.10.egg/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/setuptools-63.4.3-py3.10.egg/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/bitnami/python/lib/python3.10/site-packages/setuptools-63.4.3-py3.10.egg/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/opt/bitnami/python/lib/python3.10/site-packages/setuptools-63.4.3-py3.10.egg/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/bitnami/python/lib/python3.10/site-packages/setuptools-63.4.3-py3.10.egg/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'odoo==16.0.post20230415' distribution was not found and is required by the application
```
6. restarting the container manually seems to work and module seems functionnal.

### What is the expected behavior?

Activation of module should not fail and force a manual restart of the container.

### What do you see instead?

`pkg_resources.DistributionNotFound: The 'odoo==16.0.post20230415' distribution was not found and is required by the application
`

Seems like something is missing in the image ?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by hellozhangwei** [comment]
Maybe it is caused by incorrect image tag. try the following

```
version: '3.3'

services:
  odoo:
    image: docker.io/bitnami/odoo:16.0.20230415
```

**Comment by Yericus** [comment]
I will try to reinstall on the pi though I have now switched to testing a VPS.
