### ISSUE TITLE
Rabbitmq-cluster-operator incompatible with kubernetes 1.27

### ISSUE THREAD

**Issue by Snazzie** [bitnami/containers#34117]
### Name and Version

bitnami/rabbitmq-cluster-operator

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. have kubernetes 1.27 cluster
2. install rabbitmq-cluster-operator with configurations and values
3. rabbitmq-messaging-topology-operator pod fails

### What is the expected behavior?

pod should be healthy

### What do you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1277ad0]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:114
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc000121458, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:95 +0x7d0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0001200f0, 0x15}, {0xc00050c3e0, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:49 +0x318
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x98?)
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:328 +0x3de
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x0?)
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:203 +0x65
k8s.io/client-go/discovery.ServerGroupsAndResources({0x1b92498, 0xc00034de90})
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:413 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:376 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc000298d68)
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:651 +0x72
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:375 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x1b92498?, 0xc00034de90?})
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/k8s.io/client-go@v0.26.3/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc000492240?, {0x0, 0x0, 0xd93cc79e2c40e701?})
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0xc0001f4620?)
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc00029cb40, {0xc00068f708, 0x1, 0x0?})
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/cluster/cluster.go:159 +0x18d
sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0xc0001f4620, 0x0, 0x0, {{0x1b8f2b8, 0xc000409500}, 0x0}, 0x1, {0x0, 0x0}, ...})
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/manager/manager.go:351 +0xf9
main.main()
	/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.10.3/src/github.com/rabbitmq/rmq-messaging-topology-operator/main.go:133 +0x8d5
	```

**Comment by javsalgar** [comment]
Hi,

It looks to me that this is an issue more related to the application itself rather than the Bitnami packaging. Could you check with the upstream rabbitmq-cluster-operator devs? 

https://github.com/rabbitmq/cluster-operator

**Comment by Snazzie** [comment]
installed chart manually. no issues. i think its something to do with argocd that im using to install the chart
