### ISSUE TITLE
Jasperreports deployment script crash

### ISSUE THREAD

**Issue by maiolif** [bitnami/containers#36054]
### Name and Version

bitnami/jasperreports:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. docker-compose build from Dockerfile to add font jar.
```Dockerfile
FROM docker.io/bitnami/jasperreports:8 
COPY fonts.jar /opt/bitnami/jasperreports/WEB-INF/lib 
```
2. The container is building and working from the image, adding `COPY` it crashes during deployment script execution

### What is the expected behavior?

Normal startup

### What do you see instead?

From BITNAMI DEBUG
```
jasperreports_1  | deploy-webapp:
jasperreports_1  |      [echo] About to copy JDBC driver for import-export config (if it exists):
jasperreports_1  |      [echo]  --- (app-server.xml:deploy-webapp) --- 
jasperreports_1  |      [echo]     jsEdition = ce
jasperreports_1  |      [echo]  warFileDistSourceDir = /opt/bitnami/jasperreports/buildomatic/../jasperserver.war
jasperreports_1  |      [echo]    warTargetDir = /opt/bitnami/tomcat/webapps/jasperserver
jasperreports_1  |      [echo]      webAppName = jasperserver
jasperreports_1  |      [echo]    webAppNameCE = jasperserver
jasperreports_1  |      [echo]   webAppNamePro = jasperserver-pro
jasperreports_1  |      [echo]   webAppNameSrc = jasperserver 
jasperreports_1  |      [echo]   webAppNameDel = jasperserver
jasperreports_1  |      [echo]  warTargetDirDel = ${warTargetDirDel}
jasperreports_1  |      [echo]  
jasperreports_1  |     [unzip] Expanding: /opt/bitnami/jasperreports/jasperserver.war into /opt/bitnami/tomcat/webapps/jasperserver
jasperreports_1  |     [unzip] Failed to change file modification time
jasperreports_1  | 
jasperreports_1  | BUILD FAILED
jasperreports_1  | /opt/bitnami/jasperreports/buildomatic/bin/app-server.xml:489: Error while expanding /opt/bitnami/jasperreports/jasperserver.war
jasperreports_1  | java.nio.file.AccessDeniedException: /opt/bitnami/tomcat/webapps/jasperserver/WEB-INF/applicationContext-export-import-web.xml
jasperreports_1  | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
jasperreports_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
jasperreports_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
jasperreports_1  | 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
jasperreports_1  | 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
jasperreports_1  | 	at java.nio.file.Files.newOutputStream(Files.java:216)
jasperreports_1  | 	at org.apache.tools.ant.taskdefs.Expand.extractFile(Expand.java:361)
jasperreports_1  | 	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:199)
jasperreports_1  | 	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:157)
jasperreports_1  | 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
jasperreports_1  | 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
jasperreports_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jasperreports_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jasperreports_1  | 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
jasperreports_1  | 	at org.apache.tools.ant.Task.perform(Task.java:350)
jasperreports_1  | 	at java.util.Vector.forEach(Vector.java:1277)
jasperreports_1  | 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
jasperreports_1  | 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
jasperreports_1  | 	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
jasperreports_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jasperreports_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jasperreports_1  | 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
jasperreports_1  | 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
jasperreports_1  | 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
jasperreports_1  | 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
jasperreports_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jasperreports_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jasperreports_1  | 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
jasperreports_1  | 	at org.apache.tools.ant.Task.perform(Task.java:350)
jasperreports_1  | 	at org.apache.tools.ant.Target.execute(Target.java:449)
jasperreports_1  | 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
jasperreports_1  | 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
jasperreports_1  | 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
jasperreports_1  | 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
jasperreports_1  | 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
jasperreports_1  | 	at org.apache.tools.ant.Main.runBuild(Main.java:818)
jasperreports_1  | 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
jasperreports_1  | 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
jasperreports_1  | 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by maiolif** [comment]
Using bitnami dockerfile build is ok, but only if not detached. I suppose the folder for fonts jar (WEB-INF/lib) is managed by tomcat after entrypoint. It's necessary to have it to put font jar in the container after building the image
