### ISSUE TITLE
KRaft controller node shutting down while renouncing leadership (NPE)

### ISSUE THREAD

**Issue by hsiadeveloper** [bitnami/containers#36365]
### Name and Version

bitnami/kafka:3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Kafka nodes in Kraft mode crash randomly because of an NPE error on the latest bitnami/kafka:3.4 image

### What do you see instead?

```
ERROR Encountered fatal fault: exception while renouncing leadership (org.apache.kafka.server.fault.ProcessExitingFaultHandler)
java.lang.NullPointerException: Cannot invoke "org.apache.kafka.timeline.BaseHashTable.baseAddOrReplace(Object)" because "this.deltaTable" is null
	at org.apache.kafka.timeline.SnapshottableHashTable$HashTier.mergeFrom(SnapshottableHashTable.java:125)
	at org.apache.kafka.timeline.Snapshot.mergeFrom(Snapshot.java:68)
	at org.apache.kafka.timeline.SnapshotRegistry.deleteSnapshot(SnapshotRegistry.java:236)
	at org.apache.kafka.timeline.SnapshotRegistry$SnapshotIterator.remove(SnapshotRegistry.java:67)
	at org.apache.kafka.timeline.SnapshotRegistry.revertToSnapshot(SnapshotRegistry.java:214)
	at org.apache.kafka.controller.QuorumController.renounce(QuorumController.java:1193)
	at org.apache.kafka.controller.QuorumController.access$2900(QuorumController.java:151)
	at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$handleLeaderChange$3(QuorumController.java:1033)
	at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$appendRaftEvent$4(QuorumController.java:1058)
	at org.apache.kafka.controller.QuorumController$ControllerEvent.run(QuorumController.java:489)
	at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:121)
	at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:201)
	at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:175)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Additional information

this has already been fixed in the 3.4.1 release, you should use this release instead of the current 3.4.0

https://issues.apache.org/jira/browse/KAFKA-14946
Fix Version/s:
3.4.1

**Comment by carrodher** [comment]
At this very moment, Kafka 3.4.1 is not released, see https://kafka.apache.org/downloads.
Once released in upstream, we will release the same version on our side
