### ISSUE TITLE
[bitnami/elasticsearch] container not starting

### ISSUE THREAD

**Issue by techsachin1** [bitnami/containers#38454]
### Name and Version

bitnami/elasticsearch

### What is the problem this feature will solve?
```
elasticsearch 16:00:53.10 INFO  ==> ** Starting Elasticsearch **
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
```
output:
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
# An error report file with more information is saved as:
# logs/hs_err_pid447.log
error:
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Not enough space' (errno=12)
        at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
        at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
```

**Comment by techsachin1** [comment]
machine have sufficient space n java installed

**Comment by javsalgar** [comment]
Hi,

Could you add more details of the platform you are using to run Elasticsearch? It seems to me that there may be inside a VM without enough mapped memory or maybe the kernel is not allowing the memory operation.
