### ISSUE TITLE
[bitnami/kafka] Container exits when connecting with SASL_SSL (plain)

### ISSUE THREAD

**Issue by Amogh-Bharadwaj** [bitnami/containers#38840]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

My docker compose file:
```
version: '2'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka.example.com
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://kafka.example.com:9092
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
      - KAFKA_TLS_CLIENT_AUTH=none
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_TLS_TYPE=PEM
      - BITNAMI_DEBUG=true
    volumes:
      - './keystore/kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      - './truststore/ca-key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      - './truststore/kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
      - './kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf:ro'

```

My `kafka_jaas.conf` file: 
```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="user"
  password="password";
};
```

The certificates here were generated using the script in the docs.
Used the same password for everything.
Step to reproduce is simply running `docker compose up`.

### What is the expected behavior?

The server starts running and does not exit immediately.

### What do you see instead?

The following error:

```docker
 org.apache.kafka.common.KafkaException: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
 	at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
 	at kafka.network.Processor.<init>(SocketServer.scala:922)
 	at kafka.network.Acceptor.newProcessor(SocketServer.scala:830)
 	at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:800)
 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
 	at kafka.network.Acceptor.addProcessors(SocketServer.scala:799)
 	at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:503)
 	at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:228)
 	at kafka.network.SocketServer.$anonfun$new$31(SocketServer.scala:173)
 	at kafka.network.SocketServer.$anonfun$new$31$adapted(SocketServer.scala:173)
 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
 	at kafka.network.SocketServer.<init>(SocketServer.scala:173)
 	at kafka.server.BrokerServer.startup(BrokerServer.scala:238)
 	at kafka.server.KafkaRaftServer.$anonfun$startup$2(KafkaRaftServer.scala:99)
 	at kafka.server.KafkaRaftServer.$anonfun$startup$2$adapted(KafkaRaftServer.scala:99)
 	at scala.Option.foreach(Option.scala:407)
 	at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:99)
 	at kafka.Kafka$.main(Kafka.scala:115)
 	at kafka.Kafka.main(Kafka.scala)
 Caused by: org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
 	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:102)
 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180)
 	... 22 more
```

### Additional information
This error occurs after successful kafka setup.
This was seen in a 2021 MacBook M1 pro

**Comment by CeliaGMqrz** [comment]
Hi @Amogh-Bharadwaj

Sorry for the delay. 

Thanks for reporting the issue.

I have been able to reproduce the issue. Unfortunately, according to the logic established at the moment, to fix this, you can try the following:

```.yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"
services:
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka.example.com
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SASL_SSL,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ADVERTISED_LISTENERS=client://kafka.example.com:9092
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      #- KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
      - KAFKA_TLS_CLIENT_AUTH=none
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CLIENT_USERS=user
      #- KAFKA_CLIENT_PASSWORDS=password
      #- KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_TLS_TYPE=PEM
      - BITNAMI_DEBUG=true
    volumes:
      - "kafka_data:/bitnami"
      - './certs/tls.crt:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      - './certs/tls.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      - './certs/ca.crt:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
      - './kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf:ro'

volumes:
  kafka_data:
    driver: local
```
You can generate certificates as follows:

```
#!/bin/bash

mkdir certs
# Root CA
openssl genrsa -out certs/ca.key 2048
openssl req -new -x509 -sha256 \
        -subj "/CN=CA" \
        -key certs/ca.key -out certs/ca.crt

# Kafka cert
openssl genrsa -out certs/node-key-temp.pem 2048
openssl pkcs8 -inform PEM -outform PEM -in certs/node-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out certs/tls.key

openssl req -new \
        -subj "/CN=kafka" \
        -key certs/tls.key -out certs/tls.csr
cat > certs/v3.ext << EOF
subjectAltName = @alt_names

[alt_names]
DNS.1 = kafka.example.com
EOF
openssl x509 -req -in certs/tls.csr -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial -sha256 -extfile certs/v3.ext \-out certs/tls.crt
# Cleanup
rm certs/*-temp.pem
rm certs/*.csr
rm certs/*.srl
```
The team is working on a new version that simplifies this configuration. If the problem persists, please let us know.  Sorry for the inconvenience.

Thanks for the feedback!
