### ISSUE TITLE
AWS command execution fails on bitnami/aws-cli

### ISSUE THREAD

**Issue by aii-shanker-jj** [bitnami/containers#40781]
### Name and Version

bitnami/aws-cli:lastest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Running `bitnami/aws-cli:latest` running as a container in RKE2 Kubernetes.
2. Created a script to generate docker token in a loop `aws ecr get-login-password --region ${REGION} --profile $AWS_PROF`
> For the first iteration it works perfectly.
> Second iteration fails with error.

### What is the expected behavior?

During the AWS command execution in a iterative loop also we shouldn't face the following error 
```
[Errno 30] Read-only file system: '/.aws/cli'
```

### What do you see instead?

Created a script to generate docker token in a loop `aws ecr get-login-password --region ${REGION} --profile $AWS_PROF`
> For the first iteration it works perfectly.
> Second iteration fails with the following error.
```
[Errno 30] Read-only file system: '/.aws/cli'
```

upon debugging following error was displayed.
```
2023-07-12 03:30:03,512 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sts.AssumeRole: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7ff4afc60110>>
2023-07-12 03:30:03,512 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2023-07-12 03:30:03,512 - MainThread - botocore.hooks - DEBUG - Event after-call.sts.AssumeRole: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7ff4afc53910>>
2023-07-12 03:30:03,513 - MainThread - botocore.credentials - WARNING - Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 496, in _protected_refresh
    metadata = self._refresh_using()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 637, in fetch_credentials
    return self._get_cached_credentials()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 648, in _get_cached_credentials
    self._write_to_cache(response)
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 673, in _write_to_cache
    self._cache[self._cache_key] = deepcopy(response)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/utils.py", line 3255, in __setitem__
    os.makedirs(self._working_dir)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/.aws/cli'
2023-07-12 03:30:03,524 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/clidriver.py", line 460, in main
    return command_table[parsed_args.command](remaining, parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/clidriver.py", line 595, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/customizations/commands.py", line 205, in __call__
    rc = self._run_main(parsed_args, parsed_globals)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/customizations/ecr.py", line 40, in _run_main
    result = ecr_client.get_authorization_token()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/client.py", line 341, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/client.py", line 683, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/client.py", line 703, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/endpoint.py", line 101, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/endpoint.py", line 131, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/endpoint.py", line 114, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/signers.py", line 94, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/signers.py", line 158, in sign
    auth = self.get_auth_instance(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/signers.py", line 253, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 585, in get_frozen_credentials
    self._refresh()
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 480, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 496, in _protected_refresh
    metadata = self._refresh_using()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 637, in fetch_credentials
    return self._get_cached_credentials()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 648, in _get_cached_credentials
    self._write_to_cache(response)
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/credentials.py", line 673, in _write_to_cache
    self._cache[self._cache_key] = deepcopy(response)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/aws-cli/venv/lib/python3.11/site-packages/awscli/botocore/utils.py", line 3255, in __setitem__
    os.makedirs(self._working_dir)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/.aws/cli'
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami aws-cli container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by aii-shanker-jj** [comment]
I did mount the host path to `/.aws` path of the container, which made the trouble.
Now I have moved to a different path and it works fine.
