### ISSUE TITLE
[bitnami/keycloak] SQL Exception with Keycloak image

### ISSUE THREAD

**Issue by ice09** [bitnami/containers#40909]
### Name and Version

bitname/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Start a new container with
`docker run --name my-bitnami-keycloak -p 8080:8080 -e KEYCLOAK_DATABASE_VENDOR=dev-mem bitnami/keycloak`
2. After startup, login is possible, no errors

Wait for some minutes (scheduler?). No further action necessary.

Exception below occurs in log.

### What is the expected behavior?

No exceptions.

### What do you see instead?
<details><summary>Logs</summary>

```
2023-07-13 06:10:24,679 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 42104, SQLState: 42S04
2023-07-13 06:10:24,680 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) Table "REALM" not found (this database is empty); SQL statement:
select distinct realmentit0_.EVENTS_EXPIRATION as col_0_0_ from REALM realmentit0_ where realmentit0_.EVENTS_EXPIRATION>0 [42104-214]
2023-07-13 06:10:24,691 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredEvents: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
        at org.hibernate.query.Query.getResultList(Query.java:165)
        at org.keycloak.events.jpa.JpaEventStoreProvider.clearExpiredEvents(JpaEventStoreProvider.java:99)
        at org.keycloak.services.scheduled.ClearExpiredEvents.run(ClearExpiredEvents.java:39)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.lambda$run$0(ScheduledTaskRunner.java:56)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:50)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
        at org.hibernate.loader.Loader.doQuery(Loader.java:956)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
        at org.hibernate.loader.Loader.doList(Loader.java:2868)
        at org.hibernate.loader.Loader.doList(Loader.java:2850)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
        at org.hibernate.loader.Loader.list(Loader.java:2677)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:218)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
        ... 15 more
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "REALM" not found (this database is empty); SQL statement:
select distinct realmentit0_.EVENTS_EXPIRATION as col_0_0_ from REALM realmentit0_ where realmentit0_.EVENTS_EXPIRATION>0 [42104-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8385)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
        at org.h2.command.Parser.readTableOrView(Parser.java:8358)
        at org.h2.command.Parser.readTablePrimary(Parser.java:1863)
        at org.h2.command.Parser.readTableReference(Parser.java:2334)
        at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
        at org.h2.command.Parser.parseSelect(Parser.java:2878)
        at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
        at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
        at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
        at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
        at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
        at org.h2.command.Parser.parseQuery(Parser.java:2567)
        at org.h2.command.Parser.parsePrepared(Parser.java:724)
        at org.h2.command.Parser.parse(Parser.java:689)
        at org.h2.command.Parser.parse(Parser.java:661)
        at org.h2.command.Parser.prepareCommand(Parser.java:569)
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
        at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:658)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
        ... 31 more

2023-07-13 06:10:24,698 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 42104, SQLState: 42S04
2023-07-13 06:10:24,698 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) Table "CLIENT_INITIAL_ACCESS" not found (this database is empty); SQL statement:
delete from CLIENT_INITIAL_ACCESS where EXPIRATION>0 and TIMESTAMP+EXPIRATION<? or REMAINING_COUNT=0 [42104-214]
2023-07-13 06:10:24,699 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredClientInitialAccessTokens: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1705)
        at org.keycloak.models.jpa.JpaRealmProvider.removeExpiredClientInitialAccess(JpaRealmProvider.java:1055)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.removeExpiredClientInitialAccess(RealmCacheSession.java:1400)
        at org.keycloak.services.scheduled.ClearExpiredClientInitialAccessTokens.run(ClearExpiredClientInitialAccessTokens.java:30)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.lambda$run$0(ScheduledTaskRunner.java:56)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:50)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:81)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:68)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:50)
        at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:177)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:458)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:376)
        at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1483)
        at org.hibernate.query.internal.AbstractProducedQuery.doExecuteUpdate(AbstractProducedQuery.java:1714)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1696)
        ... 15 more
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CLIENT_INITIAL_ACCESS" not found (this database is empty); SQL statement:
delete from CLIENT_INITIAL_ACCESS where EXPIRATION>0 and TIMESTAMP+EXPIRATION<? or REMAINING_COUNT=0 [42104-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8385)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
        at org.h2.command.Parser.readTableOrView(Parser.java:8358)
        at org.h2.command.Parser.readTableOrView(Parser.java:8328)
        at org.h2.command.Parser.readSimpleTableFilter(Parser.java:1160)
        at org.h2.command.Parser.parseDelete(Parser.java:1174)
        at org.h2.command.Parser.parsePrepared(Parser.java:774)
        at org.h2.command.Parser.parse(Parser.java:689)
        at org.h2.command.Parser.parse(Parser.java:661)
        at org.h2.command.Parser.prepareCommand(Parser.java:569)
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
        at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:658)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:90)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
        ... 24 more

2023-07-13 06:10:24,700 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 42104, SQLState: 42S04
2023-07-13 06:10:24,701 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) Table "REALM" not found (this database is empty); SQL statement:
select realmentit0_.ID as col_0_0_ from REALM realmentit0_ [42104-214]
2023-07-13 06:10:24,701 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredUserSessions: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
        at org.hibernate.loader.Loader.scroll(Loader.java:2945)
        at org.hibernate.loader.hql.QueryLoader.scroll(QueryLoader.java:610)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.scroll(QueryTranslatorImpl.java:452)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performScroll(HQLQueryPlan.java:352)
        at org.hibernate.internal.SessionImpl.scroll(SessionImpl.java:1601)
        at org.hibernate.query.internal.AbstractProducedQuery.doScroll(AbstractProducedQuery.java:1588)
        at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1574)
        at org.hibernate.query.internal.AbstractProducedQuery.stream(AbstractProducedQuery.java:1598)
        at org.hibernate.query.Query.getResultStream(Query.java:1140)
        at org.keycloak.models.jpa.JpaRealmProvider.getRealms(JpaRealmProvider.java:148)
        at org.keycloak.models.jpa.JpaRealmProvider.getRealmsStream(JpaRealmProvider.java:144)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmsStream(RealmCacheSession.java:484)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.removeAllExpired(InfinispanUserSessionProvider.java:614)
        at org.keycloak.services.scheduled.ClearExpiredUserSessions.run(ClearExpiredUserSessions.java:39)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.runTask(ScheduledTaskRunner.java:69)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.lambda$run$0(ScheduledTaskRunner.java:56)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:50)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "REALM" not found (this database is empty); SQL statement:
select realmentit0_.ID as col_0_0_ from REALM realmentit0_ [42104-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8385)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
        at org.h2.command.Parser.readTableOrView(Parser.java:8358)
        at org.h2.command.Parser.readTablePrimary(Parser.java:1863)
        at org.h2.command.Parser.readTableReference(Parser.java:2334)
        at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
        at org.h2.command.Parser.parseSelect(Parser.java:2878)
        at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
        at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
        at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
        at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
        at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
        at org.h2.command.Parser.parseQuery(Parser.java:2567)
        at org.h2.command.Parser.parsePrepared(Parser.java:724)
        at org.h2.command.Parser.parse(Parser.java:689)
        at org.h2.command.Parser.parse(Parser.java:661)
        at org.h2.command.Parser.prepareCommand(Parser.java:569)
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
        at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:658)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
        ... 27 more

2023-07-13 06:10:24,711 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 42104, SQLState: 42S04
2023-07-13 06:10:24,711 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) Table "REALM_ATTRIBUTE" not found (this database is empty); SQL statement:
select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=? and length(realmattri0_.VALUE)>0 [42104-214]
2023-07-13 06:10:24,712 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredAdminEvents: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
        at org.hibernate.loader.Loader.scroll(Loader.java:2945)
        at org.hibernate.loader.hql.QueryLoader.scroll(QueryLoader.java:610)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.scroll(QueryTranslatorImpl.java:452)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performScroll(HQLQueryPlan.java:352)
        at org.hibernate.internal.SessionImpl.scroll(SessionImpl.java:1601)
        at org.hibernate.query.internal.AbstractProducedQuery.doScroll(AbstractProducedQuery.java:1588)
        at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1574)
        at org.hibernate.query.internal.AbstractProducedQuery.stream(AbstractProducedQuery.java:1598)
        at org.hibernate.query.Query.getResultStream(Query.java:1140)
        at org.keycloak.events.jpa.JpaEventStoreProvider.clearExpiredAdminEvents(JpaEventStoreProvider.java:283)
        at org.keycloak.events.jpa.JpaEventStoreProviderFactory.invalidate(JpaEventStoreProviderFactory.java:69)
        at org.keycloak.services.DefaultKeycloakSessionFactory.lambda$invalidate$0(DefaultKeycloakSessionFactory.java:367)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.keycloak.services.DefaultKeycloakSessionFactory.invalidate(DefaultKeycloakSessionFactory.java:367)
        at org.keycloak.services.DefaultKeycloakSession.invalidate(DefaultKeycloakSession.java:124)
        at org.keycloak.services.scheduled.ClearExpiredAdminEvents.run(ClearExpiredAdminEvents.java:35)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.lambda$run$0(ScheduledTaskRunner.java:56)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:50)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "REALM_ATTRIBUTE" not found (this database is empty); SQL statement:
select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=? and length(realmattri0_.VALUE)>0 [42104-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8385)
        at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8369)
        at org.h2.command.Parser.readTableOrView(Parser.java:8358)
        at org.h2.command.Parser.readTablePrimary(Parser.java:1863)
        at org.h2.command.Parser.readTableReference(Parser.java:2334)
        at org.h2.command.Parser.parseSelectFromPart(Parser.java:2772)
        at org.h2.command.Parser.parseSelect(Parser.java:2878)
        at org.h2.command.Parser.parseQueryPrimary(Parser.java:2762)
        at org.h2.command.Parser.parseQueryTerm(Parser.java:2633)
        at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2612)
        at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2605)
        at org.h2.command.Parser.parseQueryExpression(Parser.java:2598)
        at org.h2.command.Parser.parseQuery(Parser.java:2567)
        at org.h2.command.Parser.parsePrepared(Parser.java:724)
        at org.h2.command.Parser.parse(Parser.java:689)
        at org.h2.command.Parser.parse(Parser.java:661)
        at org.h2.command.Parser.prepareCommand(Parser.java:569)
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
        at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:658)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
        ... 45 more
```

</details>

### Additional information

Note: This happens with `dev-mem` and no further configuration.

Tested version was 21.1.2.

**Comment by dalbani** [comment]
I personally haven't been able to reproduce this issue.
I am also wondering how this behavior could be specific to the Bitnami flavored image, and not to Keycloak itself.

**Comment by ice09** [comment]
I am using Bitnami for the first time, when I used keycloak/keycloak and started in "dev" mode (which uses H2), I never had this issue, as well as when I am using keycloak/keycloak against an Oracle database in "prod" mode. So it seems to be the configuration which Bitnami uses by default (maybe be distributed caching related?).

**Comment by dalbani** [comment]
The Bitnami image pretty much repackages Keycloak with no functional changes, so I don't see how such a Bitnami specific problem could happen.
But more than my guess, as I said above, I haven't been able to reproduce the issue (no such errors are logged).
Can you try again (from a clean environment)? Or precisely give more information of your environment, as it may matter.

**Comment by dalbani** [comment]
As usual in a debugging session, 5 minutes after I wrote my message above... I got the errors that you mentioned, @ice09 🥵 
I though it was a few minutes as you initially wrote but actually, it's exactly 15 minutes:
```
2023-07-14 11:44:37,903 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
2023-07-14 11:59:37,706 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 42104, SQLState: 42S04
```
I'll investigate further.

**Comment by dalbani** [comment]
I've just checked with vanilla Keycloak 22 and I get the same errors.
See my comment on https://github.com/keycloak/keycloak/issues/13252#issuecomment-1635822239.

**Comment by ice09** [comment]
Thanks for investigating! I didn't realize that "dev-mem" is also an option with the official image as "start-dev" always spins up a H2 which I am using then. So you are right, this is not Bitnami related and can be closed (I can do it as well).

**Comment by ice09** [comment]
Just to add: this works well with "dev-file" which is the default for the standard image keycloak/keycloak. So this is a Keycloak image related issue and if "dev-file" is used (which is the default with "start-dev" with the Keycloak image) the error does not occur, only with "dev-mem".
