### ISSUE TITLE
[bitnami/zookeeper] Zookeeper No Auth for /services

### ISSUE THREAD

**Issue by WhiteStart** [bitnami/containers#40906]
### Name and Version

bitnami/zookeeper:3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```yaml
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user
      - ZOO_SERVER_PASSWORDS=password
      - ZOO_CLIENT_USER=user
      - ZOO_CLIENT_PASSWORD=password
    networks:
      - zk-kafka

volumes:
  zookeeper_data:
    driver: local
```
In Springboot
```
        curatorFramework = CuratorFrameworkFactory.builder()
                .authorization("digest", "user:password".getBytes(StandardCharsets.UTF_8))
                // 127.0.0.1:2181
                .connectString(propertiesConfig.getConnectString())
                .sessionTimeoutMs(propertiesConfig.getSessionTimeout())
                .connectionTimeoutMs(propertiesConfig.getConnectionTimeout())
                .retryPolicy(new ExponentialBackoffRetry(1000, 3))
                .build();
        curatorFramework.start();
        return curatorFramework;

digestString = "user:password";
        // 将明文账户密码通过api生成密文
        String digest = DigestAuthenticationProvider.generateDigest(digestString);
        ACL acl = new ACL(ZooDefs.Perms.ALL, new Id("digest", digest));
        list.add(acl);
curatorFramework.create()
                        .creatingParentsIfNeeded()
                        .withMode(CreateMode.PERSISTENT)
                        // 根据预设的账户密码登录，保证只有该账户可以操作相关节点
                        .withACL(list, true)
                        .forPath(registrationPath);
```

### What do you see instead?
```
Caused by: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /services
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:120) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1347) ~[zookeeper-3.8.0.jar:3.8.0]
	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:351) ~[curator-client-5.2.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl$18.call(CreateBuilderImpl.java:1222) ~[curator-framework-5.2.0.jar:5.2.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl$18.call(CreateBuilderImpl.java:1193) ~[curator-framework-5.2.0.jar:5.2.0]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93) ~[curator-client-5.2.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1190) ~[curator-framework-5.2.0.jar:5.2.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605) ~[curator-framework-5.2.0.jar:5.2.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595) ~[curator-framework-5.2.0.jar:5.2.0]
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:48) ~[curator-framework-5.2.0.jar:5.2.0]
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.internalRegisterService(ServiceDiscoveryImpl.java:237) ~[curator-x-discovery-5.1.0.jar:na]
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.registerService(ServiceDiscoveryImpl.java:192) ~[curator-x-discovery-5.1.0.jar:na]
	at org.springframework.cloud.zookeeper.serviceregistry.ZookeeperServiceRegistry.register(ZookeeperServiceRegistry.java:71) ~[spring-cloud-zookeeper-discovery-3.1.1.jar:3.1.1]
	... 28 common frames omitted
```

**Comment by WhiteStart** [comment]
I solved this by add vm options -Djava.security.auth.login.config=provider/src/main/resources/jaas.conf
Client {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="user"
    password="password";
};

Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user="user"
    password="password";
};

and add this in application.yml
zookeeper:
    connect-string: 127.0.0.1:2181
    enabled: true
    properties:
      authProvider.1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      requireClientAuthScheme: sasl
      jaasLoginRenew: 3600000
