### ISSUE TITLE
[bitnami/kafka] kafka:3.3.2-debian-11-r183 breaks "No security protocol defined for listener PLAINTEXT"

### ISSUE THREAD

**Issue by jheijmans** [bitnami/containers#43918]
### Name and Version

bitnami/kafka:3.3.2-debian-11-r183

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a Docker Compose file with the following setup:
```
version: "3.6"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.3.2-debian-11-r183' 
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ADVERTISED_HOST=localhost
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 5s
      retries: 10
    depends_on:
      - zookeeper
```
2. Launch it (e.g. docker compose up -d --wait)
3. Observe that the Kafka container fails to start with the following error
```
[2023-08-08 05:26:15,535] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
2023-08-08T05:26:15.538372764Z java.lang.IllegalArgumentException: Error creating broker listeners from 'PLAINTEXT://:9092': No security protocol defined for listener PLAINTEXT
2023-08-08T05:26:15.538376908Z 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:273)
2023-08-08T05:26:15.538380740Z 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:252)
2023-08-08T05:26:15.538384081Z 	at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:1956)
2023-08-08T05:26:15.538387182Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1694)
2023-08-08T05:26:15.538390701Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1495)
2023-08-08T05:26:15.538393979Z 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1418)
2023-08-08T05:26:15.538411440Z 	at kafka.Kafka$.buildServer(Kafka.scala:67)
2023-08-08T05:26:15.538415363Z 	at kafka.Kafka$.main(Kafka.scala:87)
2023-08-08T05:26:15.538561172Z 	at kafka.Kafka.main(Kafka.scala)
2023-08-08T05:26:15.538566942Z Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener PLAINTEXT
2023-08-08T05:26:15.538570881Z 	at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:49)
2023-08-08T05:26:15.538574797Z 	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:110)
2023-08-08T05:26:15.538578166Z 	at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:49)
2023-08-08T05:26:15.538581583Z 	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:54)
2023-08-08T05:26:15.538584991Z 	at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:270)
2023-08-08T05:26:15.538588418Z 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
2023-08-08T05:26:15.538591646Z 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
2023-08-08T05:26:15.538595233Z 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
2023-08-08T05:26:15.538599151Z 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
2023-08-08T05:26:15.538602528Z 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
2023-08-08T05:26:15.538606513Z 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
2023-08-08T05:26:15.538609789Z 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
2023-08-08T05:26:15.538613730Z 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:270)
2023-08-08T05:26:15.538617450Z 	... 8 more
```
4. Try again but change the kafka image to r181 - observe it starts without problems

### What is the expected behavior?

I expect the behavior to be the same as with the r181 revision of the image

### What do you see instead?

The Kafka container fails to start with the following error
```
[2023-08-08 05:26:15,535] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
2023-08-08T05:26:15.538372764Z java.lang.IllegalArgumentException: Error creating broker listeners from 'PLAINTEXT://:9092': No security protocol defined for listener PLAINTEXT
2023-08-08T05:26:15.538376908Z 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:273)
2023-08-08T05:26:15.538380740Z 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:252)
2023-08-08T05:26:15.538384081Z 	at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:1956)
2023-08-08T05:26:15.538387182Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1694)
2023-08-08T05:26:15.538390701Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1495)
2023-08-08T05:26:15.538393979Z 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1418)
2023-08-08T05:26:15.538411440Z 	at kafka.Kafka$.buildServer(Kafka.scala:67)
2023-08-08T05:26:15.538415363Z 	at kafka.Kafka$.main(Kafka.scala:87)
2023-08-08T05:26:15.538561172Z 	at kafka.Kafka.main(Kafka.scala)
2023-08-08T05:26:15.538566942Z Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener PLAINTEXT
2023-08-08T05:26:15.538570881Z 	at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:49)
2023-08-08T05:26:15.538574797Z 	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:110)
2023-08-08T05:26:15.538578166Z 	at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:49)
2023-08-08T05:26:15.538581583Z 	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:54)
2023-08-08T05:26:15.538584991Z 	at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:270)
2023-08-08T05:26:15.538588418Z 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
2023-08-08T05:26:15.538591646Z 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
2023-08-08T05:26:15.538595233Z 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
2023-08-08T05:26:15.538599151Z 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
2023-08-08T05:26:15.538602528Z 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
2023-08-08T05:26:15.538606513Z 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
2023-08-08T05:26:15.538609789Z 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
2023-08-08T05:26:15.538613730Z 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:270)
2023-08-08T05:26:15.538617450Z 	... 8 more
```

**Comment by migruiz4** [comment]
Hi @jheijmans,

Thank you for reporting this issue.

Due to #42309, the latest version of the bitnami/kafka image is setting these env variables inside Kafka server.properties with an empty value.

As a workaround, you could use the following docker-compose:
```
version: "3.6"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.3.2-debian-11-r183' 
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_HOST=localhost
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 5s
      retries: 10
    depends_on:
      - zookeeper
```

- Added `KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT` (mandatory)
- Added `KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT` to workaround the 'empty value' issue.
- Removed `KAFKA_ENABLE_KRAFT` no longer needed.
- Removed `ALLOW_PLAINTEXT_LISTENER` no longer needed.

**Comment by jheijmans** [comment]
@migruiz4 thanks for your swift response. The proposed workaround works for me.
