### ISSUE TITLE
[bitnami/kafka] Spring Boot SASL Kafka Producer Unexpected Kafka request of type METADATA during SASL handshake

### ISSUE THREAD

**Issue by Unique201** [bitnami/containers#44623]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Currently have Kafka broker set up using docker-compose with the following:

```yaml
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://:9091,DOCKER_COMPOSE://:9092,MINIKUBE://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://localhost:9091,DOCKER_COMPOSE://host.docker.internal:9092,MINIKUBE://host.minikube.internal:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,DOCKER_COMPOSE:SASL_PLAINTEXT,MINIKUBE:SASL_PLAINTEXT
      - KAFKA_CLIENT_USERS=test
      - KAFKA_CLIENT_PASSWORDS=test
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OPTS=-Djavax.net.debug=ssl
      - KAFKA_OPTS=-Dsun.security.krb5.debug=true
```
It works then when trying to set up a producer / consumer from within the docker container with the following .properties file:

```
bootstrap.servers=host.docker.internal:9092
compression.type=none
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="test" password="test";
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
```

When inside the container:

```console
$ kafka-console-producer.sh --bootstrap-server 127.0.0.1:9092 --topic test --producer.config /opt/bitnami/kafka/config/producer.properties
>Hi there!
>This is a test
$ kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic test --consumer.config /opt/bitnami/kafka/config/consumer.properties
Hi there!
This is a test
```
I have a Spring web app that I am trying to connect a Producer to 9092 with the following setup :
```
*application.properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic-name=Event
spring.kafka.producer.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.producer.properties.sasl.mechanism=PLAIN
spring.kafka.producer.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="test" password="test";
```

```
@Service
@Log4j2
@NoArgsConstructor
public class KafkaProducer
{
    @Autowired
    private KafkaTemplate<String, String> kafkaTemplate;    


    public void sendMessage(String topic, String message) {
        kafkaTemplate.send(topic, message);
    }
}

```

Is there something fundamentally I am misunderstanding when trying to set up a Producer to connect with the broker with SASL?

I have also tried the following way to set the configurations for the producer with same results:

```
    @Bean
    public KafkaTemplate<String, String> kafkaTemplate() {
        return new KafkaTemplate<>(producerFactory());
    }

    @Bean
    public ProducerFactory<String, String> producerFactory() {
        Map<String, Object> props = new HashMap<>();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        ProducerConfig.
        props.put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, "SASL_PLAINTEXT");
        props.put(SaslConfigs.SASL_MECHANISM, "PLAIN");
        props.put(SaslConfigs.SASL_JAAS_CONFIG, String.format(
                "%s required username=\"%s\" " + "password=\"%s\";", PlainLoginModule.class.getName(), "test", "test"
        ));
            
        return new DefaultKafkaProducerFactory<>(props);
    }
```

### What is the expected behavior?

Expecting kafka producer to connect to kafka broker with SASL authentication

### What do you see instead?

I then receive the following errors:
In the docker container-
`[2023-08-14 08:52:39,228] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1003] Failed authentication (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)`
In the Spring app - 

```
11:09:19.106 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.Metadata - [Producer clientId=producer-1] Updating last seen epoch for partition Event-0 from 2 to epoch 2 from new metadata
11:09:19.106 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.Metadata - [Producer clientId=producer-1] Requesting metadata update for partition Event-0 due to error LEADER_NOT_AVAILABLE
11:09:19.106 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.Metadata - [Producer clientId=producer-1] Updated cluster metadata updateVersion 24 to MetadataCache{clusterId='7pTzPdvwRryMKXh0hkz9mg', nodes={1003=host.docker.internal:9092 (id: 1003 rack: null)}, partitions=[PartitionMetadata(error=LEADER_NOT_AVAILABLE, partition=Event-0, leader=Optional.empty, leaderEpoch=Optional[2], replicas=1001, isr=1001, offlineReplicas=1001)], controller=host.docker.internal:9092 (id: 1003 rack: null)}
11:09:19.106 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.producer.internals.Sender - [Producer clientId=producer-1] Requesting metadata update due to unknown leader topics from the batched records: [Event]
11:09:19.206 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.producer.internals.Sender - [Producer clientId=producer-1] Requesting metadata update due to unknown leader topics from the batched records: [Event]
11:09:19.206 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Sending metadata request MetadataRequestData(topics=[MetadataRequestTopic(topicId=AAAAAAAAAAAAAAAAAAAAAA, name='Event')], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false) to node host.docker.internal:9092 (id: 1003 rack: null)
11:09:19.206 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Sending METADATA request with header RequestHeader(apiKey=METADATA, apiVersion=12, clientId=producer-1, correlationId=26) and timeout 30000 to node 1003: MetadataRequestData(topics=[MetadataRequestTopic(topicId=AAAAAAAAAAAAAAAAAAAAAA, name='Event')], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false)
11:09:19.207 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.producer.internals.Sender - [Producer clientId=producer-1] Requesting metadata update due to unknown leader topics from the batched records: [Event]
11:09:19.207 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.common.network.Selector - [AdminClient clientId=adminclient-1] Connection with localhost/127.0.0.1 disconnected
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674) ~[kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576) [kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481) [kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560) [kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1400) [kafka-clients-3.1.2.jar:?]
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1331) [kafka-clients-3.1.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
11:09:19.208 [kafka-admin-client-thread | adminclient-1] INFO  org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Node -1 disconnected.
11:09:19.208 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Cancelled in-flight METADATA request with correlation id 13 due to node -1 being disconnected (elapsed time since creation: 105ms, elapsed time since send: 105ms, request timeout: 435ms): MetadataRequestData(topics=[], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false)
11:09:19.208 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.KafkaAdminClient - [AdminClient clientId=adminclient-1] Call(callName=fetchMetadata, deadlineMs=1692007759538, tries=7, nextAllowedTryMs=1692007759308) failed: DisconnectException: Cancelled fetchMetadata request with correlation id 13 due to node -1 being disconnected. Beginning retry #7
11:09:19.209 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Received METADATA response from node 1003 for request with header RequestHeader(apiKey=METADATA, apiVersion=12, clientId=producer-1, correlationId=26): MetadataResponseData(throttleTimeMs=0, brokers=[MetadataResponseBroker(nodeId=1003, host='host.docker.internal', port=9092, rack=null)], clusterId='7pTzPdvwRryMKXh0hkz9mg', controllerId=1003, topics=[MetadataResponseTopic(errorCode=0, name='Event', topicId=saMiTZA0RveaLhcBgf3IYw, isInternal=false, partitions=[MetadataResponsePartition(errorCode=5, partitionIndex=0, leaderId=-1, leaderEpoch=2, replicaNodes=[1001], isrNodes=[1001], offlineReplicas=[1001])], topicAuthorizedOperations=-2147483648)], clusterAuthorizedOperations=-2147483648)
```

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami kafka container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by OneCricketeer** [comment]
You're using kafka-clients library version 3.1.2, but broker server version 3.5, therefore metadata won't match.

Kafka clients are backwards compatible, not forward compatible
