### ISSUE TITLE
[bitnami/spark] spark running on the docker and spring boot java application running on the local machine

### ISSUE THREAD

**Issue by pretrainedjon** [bitnami/containers#44705]
### Name and Version

bitnami/spark:3.4.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.  I created an app with java for create  spark session and read file.  it worked locally without any errors: spark.setMaster(local[1]).
2. Then I set up the docker , setup the spark in the dockers and with docker- compose yml spark master with 2 workers. Containers for spark and workers created. Then from the local machine , App tried to connect to spark master, and connected and created session, then I tried to read the files from the mounted storage.  my app throws an exception [PATH_NOT_FOUND]  my code is below:
```
SparkSession sparkSession=SparkSession
                .builder()
                .master("spark://192.168.222.66:7077")
                 .getOrCreate();
       
        Dataset<Row> dataset=sparkSession
                .read()
                .format("csv")
                .option("header", true)
                .load("/mnt/123.csv");
        dataset.printSchema();
        dataset.show(15);
```
### What is the expected behavior?

here should read the file.

### What do you see instead?

but the exception is thrown:
```
org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/mnt/123.csv.
	at org.apache.spark.sql.errors.QueryCompilationErrors$.dataPathNotExistError(QueryCompilationErrors.scala:1419) ~[spark-catalyst_2.12-3.4.1.jar:3.4.1]
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:757) ~[spark-sql_2.12-3.4.1.jar:3.4.1]
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754) ~[spark-sql_2.12-3.4.1.jar:3.4.1]
	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:393) ~[spark-core_2.12-3.4.1.jar:3.4.1]
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659) ~[scala-library-2.12.17.jar:na]
	at scala.util.Success.$anonfun$map$1(Try.scala:255) ~[scala-library-2.12.17.jar:na]
	at scala.util.Success.map(Try.scala:213) ~[scala-library-2.12.17.jar:na]
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292) ~[scala-library-2.12.17.jar:na]
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33) ~[scala-library-2.12.17.jar:na]
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33) ~[scala-library-2.12.17.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64) ~[scala-library-2.12.17.jar:na]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

### Additional information

Is it possible for the app on the local machine running to read file on the docker mounted folder when to communicate with spark master?

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami Spark container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by OneCricketeer** [comment]
You need to mount that file in the Spark worker container. The "local app" is no longer "local" when you run spark-submit
