### ISSUE TITLE
Latest Azure CLI Unable to download Python Six Module 

### ISSUE THREAD

**Issue by afsalva1** [bitnami/containers#4639]
### Name and Version

bitnami/azure-cli

### What steps will reproduce the bug?

Pull Latest CLI Image 
Login Azure Using Service Principal
Try to do some Write Activity in the Azure (i.e create resource group /resource ) 

### What is the expected behavior?

RROR: Error loading command module 'acs': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'appservice': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'aro': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'batch': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'iot': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'monitor': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'netappfiles': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'network': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'rdbms': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'servicebus': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'serviceconnector': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'sqlvm': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'storage': No module named 'six'
11:13:52 DOCKER: ERROR: Error loading command module 'vm': No module named 'six'
11:13:52 DOCKER: WARNING: Auto upgrade failed. name 'exit_code' is not defined
11:13:52 DOCKER: Traceback (most recent call last):
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
11:13:52 DOCKER:     cmd_result = self.invocation.execute(args)
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute

### What do you see instead?

raceback (most recent call last):
11:13:52 DOCKER:   File "/opt/bitnami/python/lib/python3.7/runpy.py", line 193, in _run_module_as_main
11:13:52 DOCKER:     "__main__", mod_spec)
11:13:52 DOCKER:   File "/opt/bitnami/python/lib/python3.7/runpy.py", line 85, in _run_code
11:13:52 DOCKER:     exec(code, run_globals)
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/azure/cli/__main__.py", line 48, in <module>
11:13:52 DOCKER:     exit_code = cli_main(az_cli, sys.argv[1:])
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/azure/cli/__main__.py", line 35, in cli_main
11:13:52 DOCKER:     return cli.invoke(args)
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/knack/cli.py", line 243, in invoke
11:13:52 DOCKER:     exit_code = self.exception_handler(ex)
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 135, in exception_handler
11:13:52 DOCKER:     return handle_exception(ex)
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/azure/cli/core/util.py", line 58, in handle_exception
11:13:52 DOCKER:     from msrestazure.azure_exceptions import CloudError
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/msrestazure/__init__.py", line 28, in <module>
11:13:52 DOCKER:     from .azure_configuration import AzureConfiguration
11:13:52 DOCKER:   File "/opt/bitnami/azure-cli/venv/lib/python3.7/site-packages/msrestazure/azure_configuration.py", line 34, in <module>

**Comment by migruiz4** [comment]
Hi @afsalva1,

Thank you for reporting this issue.

We have released version `2.39.0-debian-11-r11` with a fix for this issue, could you please let us know if it works for you?
