### ISSUE TITLE
Extended key usage does not permit use for TLS client authentication for configuration

### ISSUE THREAD

**Issue by irparajababu** [bitnami/containers#46945]
### Name and Version

bitnami/kafka:3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am facing the below issue while running the kafka broker and controller in same node.
```
[2023-09-01 11:57:15,094] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: Extended key usage does not permit use for TLS client authentication for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:102)
        at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:73)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
        at kafka.network.Processor.<init>(SocketServer.scala:921)
        at kafka.network.Acceptor.newProcessor(SocketServer.scala:829)
        at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:799)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at kafka.network.Acceptor.addProcessors(SocketServer.scala:798)
        at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:502)
        at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:228)
        at kafka.network.SocketServer.$anonfun$new$31(SocketServer.scala:173)
        at kafka.network.SocketServer.$anonfun$new$31$adapted(SocketServer.scala:173)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at kafka.network.SocketServer.<init>(SocketServer.scala:173)
        at kafka.server.BrokerServer.startup(BrokerServer.scala:241)
        at kafka.server.KafkaRaftServer.$anonfun$startup$2(KafkaRaftServer.scala:139)
        at kafka.server.KafkaRaftServer.$anonfun$startup$2$adapted(KafkaRaftServer.scala:139)
        at scala.Option.foreach(Option.scala:407)
        at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:139)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
```
### What is the expected behavior?

It should run as expected

**Comment by carrodher** [comment]
I was not able to reproduce the issue. This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
