### ISSUE TITLE
Cannot refresh dag list

### ISSUE THREAD

**Issue by Thue77** [bitnami/containers#48639]
### Name and Version

docker.io/bitnami/airflow:2.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Whenever I press the refresh button to refresh the list of dags, I get the error log below. I am not sure if this is related to the fact that custom dags do not show up in the ui when I add them to /opt/bitnami/airflow/dags:
```
[2023-09-15T16:00:58.435+0000] {app.py:1744} ERROR - Exception on /next_run_datasets_summary [POST]
2023-09-15 18:00:58 Traceback (most recent call last):
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
2023-09-15 18:00:58     response = self.full_dispatch_request()
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
2023-09-15 18:00:58     rv = self.handle_user_exception(e)
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2023-09-15 18:00:58     rv = self.dispatch_request()
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2023-09-15 18:00:58     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/auth.py", line 53, in decorated
2023-09-15 18:00:58     return func(*args, **kwargs)
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 77, in wrapper
2023-09-15 18:00:58     return func(*args, session=session, **kwargs)
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/views.py", line 1080, in next_run_datasets_summary
2023-09-15 18:00:58     dataset_triggered_dag_ids = [
2023-09-15 18:00:58   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/www/views.py", line 1081, in <listcomp>
2023-09-15 18:00:58     dag.dag_id
2023-09-15 18:00:58 AttributeError: 'str' object has no attribute 'dag_id'
```
I have this Dockerfile:

```Dockerfile
FROM docker.io/bitnami/airflow:2.7.1

USER root

RUN mkdir -p /.vscode-server \
    && chown -R 1001 /.vscode-server

USER 1001`
```
Based on the image build from the above Dockerfile, I create the container with the following docker-compose:
```yaml
version: "3.6"
services:
    postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - './data/postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '5432:5432'
    networks:
      - my_persistent_network 
  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - './data/redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_persistent_network 
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    networks:
      - my_persistent_network 
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    networks:
      - my_persistent_network 
  airflow:
    image: airflow
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_PASSWORD=bitnami
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
      # - AIRFLOW_HOME=/opt/bitnami/airflow
    volumes:
      - ./src/airflow_dags:/opt/bitnami/airflow/dags
      - ./settings/jupyter:/root/.vscode-server
      - ./src/jupyter/apps:/opt/bitnami/spark/apps
    ports:
      - '8080:8080' 
    networks:
      - my_persistent_network 
networks:
  my_persistent_network:
    driver: bridge
```

### What is the expected behavior?

I expect to see no error when refreshing

### Additional information

After further testing, it seems to be working when I exclude example jobs.

**Comment by mdhont** [comment]
> After further testing, it seems to be working when I exclude example jobs.

Does that mean that we can consider the issue solved?
