### ISSUE TITLE
On Spark Containers How to configure JAVA TrustStore?

### ISSUE THREAD

**Issue by djpirra** [bitnami/containers#49123]
### Name and Version

bitnami/spark/3.2/debian-11

### What is the problem this feature will solve?

When running certain JAVA procedures using Spark I am getting the below error:

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
        at sun.security.validator.Validator.validate(Validator.java:271)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 61 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
        ... 67 more
```

I have tried to add the certificates to "/opt/bitnami/java/jre/lib/security/cacerts" using keytool but it didn't work.
I have also added the same certificates to /usr/local/share/ca-certificates folder and executed update-ca-certificates.

What is missing?

### What is the feature you are proposing to solve the problem?

Documentation around adding certificates for this installation.

**Comment by aoterolorenzo** [comment]
Hi @djpirra 

You can define the keystore and truststore using the container env vars for SSL configuration:

```
SPARK_SSL_ENABLED: Enable SSL configuration
SPARK_SSL_KEY_PASSWORD: The password to the private key in the key store
SPARK_SSL_KEYSTORE_PASSWORD: The password for the key store
SPARK_SSL_KEYSTORE_FILE: Location of the key store (default is /opt/bitnami/spark/conf/certs/spark-truststore.jks)
SPARK_SSL_TRUSTSTORE_PASSWORD: The password for the trust store
SPARK_SSL_TRUSTSTORE_FILE: Location of the key store (default is /opt/bitnami/spark/conf/certs/spark-keystore.jks)
```
