### ISSUE TITLE
[bitnami/grafana-image-renderer] Missing Chrome

### ISSUE THREAD

**Issue by duchymor** [bitnami/containers#51895]
### Name and Version

bitnami/grafana-image-renderer:3.8.x

### What architecture are you using?

amd64

### What steps will reproduce the bug?

After upgrading to version 3.8 of Grafana Image Renderer, rendering fails with errors in both local (docker-compose) and production (kubernetes) environments. As there's no change in the readme between 3.7 and 3.8 and the size of the newer image decreased significantly, I believe it's a bug.

### What is the expected behavior?

no error

### What do you see instead?

```
grafana-renderer-1  | {
   "level":"error",
   "message":"Request failed",
   "stack":"Error: Could not find Chrome (ver. 116.0.5845.96). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /.cache/pupp
eteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:300:27)
    at ChromeLauncher.executablePath (/opt/bit
nami/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:180:25)
    at ChromeLauncher.computeLaunchArguments (/opt/bitnami/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:37)
    at async ChromeLauncher.launch (/opt/bitnam
i/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
    at async Browser.render (/opt/bitnami/grafana-image-renderer/build/browser/browser.js:226:23)
    at async HttpServer.render (/opt/bitnami/grafana-image-renderer/build/service/http-server.js:53:28)",
   "url":"/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=T0GjjYOC3t8QUnkNDcOCCrCSO7EgYwqG&timeout=15&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2FMs2UEu_nz%2Fadmin-test%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000"
}
```

**Comment by juan131** [comment]
Hi @duchymor 

Are you able to reproduce this with `3.8.0` or also on more recent versions? I can see in the Grafana Image Renderer's changelog that a fix to detect Chromium path was introduced on `3.8.1`, see:

- https://github.com/grafana/grafana-image-renderer/blob/master/CHANGELOG.md#381-2023-09-18

**Comment by juan131** [comment]
Hi @duchymor 

Could you please retry mounting the configuration file below in the renderer container and let us know if you find the same or a different error?

```json
{
  "service": {
    "host": null,
    "port": 8081,
    "metrics": {
      "enabled": false,
      "collectDefaultMetrics": true,
      "requestDurationBuckets": [
        1,
        5,
        7,
        9,
        11,
        13,
        15,
        20,
        30
      ]
    },
    "logging": {
      "level": "info",
      "console": {
        "json": true,
        "colorize": false
      }
    },
    "security": {
      "authToken": "-"
    }
  },
  "rendering": {
    "chromeBin": "/usr/bin/chromium",
    "args": [
      "--no-sandbox",
      "--disable-gpu"
    ],
    "ignoresHttpsErrors": false,
    "timezone": null,
    "acceptLanguage": null,
    "width": 1000,
    "height": 500,
    "deviceScaleFactor": 1,
    "maxWidth": 3080,
    "maxHeight": 3000,
    "maxDeviceScaleFactor": 4,
    "pageZoomLevel": 1,
    "headed": false,
    "mode": "default",
    "emulateNetworkConditions": false,
    "clustering": {
      "monitor": false,
      "mode": "browser",
      "maxConcurrency": 5,
      "timeout": 30
    },
    "verboseLogging": false,
    "dumpio": false,
    "timingMetrics": false
  }
}
```

Apply the changes below in your Docker Compose:

```diff
version: '3.8'
services:
  grafana:
    (...)
  renderer:
    image: bitnami/grafana-image-renderer:3.8.3
    ports:
      - "8080:8080"
+   volumes:
+     - <working-directory-path>/config.json:/opt/bitnami/grafana-image-renderer/conf/config.json:ro
```

> Note: replace the `<working-directory-path>` placeholder with your actual working directory path.

**Comment by duchymor** [comment]
... which is identical to https://github.com/grafana/grafana-image-renderer/blob/master/default.json

**Comment by juan131** [comment]
Hi @duchymor 

Thanks for confirming it so! I'll send a PR to fix this.

**Comment by juan131** [comment]
Hi @duchymor 

Could you please give it a try with the image version `3.8.4-debian-11-r1`? We just released containing the fix in the chrome bin path.

**Comment by duchymor** [comment]
@juan131 OK, now it works as before
