### ISSUE TITLE
[bitnami/kafka] kafka broker crash

### ISSUE THREAD

**Issue by derekcha** [bitnami/containers#52211]
### Name and Version

bitnami/kafka:3.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I was previously using bitnami/kafka:3.4.0, and was also using zookeeper.
I am testing kraft application while using version 3.5.1.
I tried using the migration method provided in the document (https://github.com/bitnami/charts/tree/main/bitnami/kafka#migrating-from-zookeeper-early-access), but a crash occurred in the broker after step 4.
The crash error is as follows.

```
kafka 08:30:57.87 INFO  ==> Formatting storage directories to add metadata...
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: If process.roles contains just the 'broker' role, the node id 0 must not be included in the set of voters controller.quorum.voters=Set(0, 1)
        at scala.Predef$.require(Predef.scala:281)
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2246)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2160)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1568)
        at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:50)
        at scala.Option.flatMap(Option.scala:271)
        at kafka.tools.StorageTool$.main(StorageTool.scala:50)
        at kafka.tools.StorageTool.main(StorageTool.scala)
```

### What is the expected behavior?

the container should start

### What do you see instead?

exited code 1

**Comment by carrodher** [comment]
Closed as duplicated of https://github.com/bitnami/charts/issues/20496

**Comment by mshivanna** [comment]
Is there any update on this? We are trying to migrate from zookeeper to Kraft following the steps described in the README.md file
