### ISSUE TITLE
Setting JAAS config fails using compose file

### ISSUE THREAD

**Issue by LukasJansen100** [bitnami/containers#54032]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm trying to run the bitnami kafka container with KRaft, and my goal is to enable the SASL/OAUTHBEARER authentication setting.
According to the [Kafka documentations](https://kafka.apache.org/documentation/#security_sasl_oauthbearer_brokerconfig) the JAAS config has to be passed as JVM parameter to each Kafka broker.

In my compose file I'm currently trying to achieve this by first mounting the following kafka_server_jaas.conf file:
```
KafkaServer {
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
    unsecuredLoginStringClaim_sub="admin";
};
```

I know that mounting the kafka_server_jaas.conf in the container was successful as I am able to locate it in the container.
However, setting the KAFKA_OPTS with the following value:
`-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_server_jaas.conf`
Doesn't seem to work.

I am using the following compose file:
```yaml
version: '2'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    volumes:
      # Mount jaas file in container
      - ./kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_server_jaas.conf 
      - "kafka_data:/bitnami"
    environment:
      # SET JAAS
      - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_server_jaas.conf
       # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      # Authentication
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=OAUTHBEARER  # Enable SASL/OAUTHBEARER
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=OAUTHBEARER  # Set SASL mechanism for inter-broker protocol
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=OAUTHBEARER  # Set SASL mechanism for controllers communications
volumes:
  kafka_data:
    driver: local
```

To run the compose file I am using [podman-compose](https://github.com/containers/podman-compose) using:
`podman-compose up -d`

The following error is logged when I run the compose file:
```
[2023-12-21 08:56:16,338] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
�[2023-12-21 08:56:16,659] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
�[2023-12-21 08:56:16,886] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2023-12-21 08:56:16,890] INFO [ControllerServer id=0] Starting controller (kafka.server.ControllerServer)
�[2023-12-21 08:56:16,919] INFO authorizerStart completed for endpoint CONTROLLER. Endpoint is now READY. (org.apache.kafka.server.network.EndpointReadyFutures)
�[2023-12-21 08:56:17,416] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
�[2023-12-21 08:56:17,468] ERROR Encountered fatal fault: caught exception (org.apache.kafka.server.fault.ProcessTerminatingFaultHandler)
java.lang.IllegalArgumentException: Login module not specified in JAAS config
        at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:66)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:93)
        at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:74)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:143)
        at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
        at kafka.network.Processor.<init>(SocketServer.scala:973)
        at kafka.network.Acceptor.newProcessor(SocketServer.scala:879)
        at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:849)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at kafka.network.Acceptor.addProcessors(SocketServer.scala:848)
        at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:523)
        at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:251)
        at kafka.network.SocketServer.$anonfun$new$29(SocketServer.scala:172)
        at kafka.network.SocketServer.$anonfun$new$29$adapted(SocketServer.scala:172)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at kafka.network.SocketServer.<init>(SocketServer.scala:172)
        at kafka.server.ControllerServer.startup(ControllerServer.scala:183)
        at kafka.server.KafkaRaftServer.$anonfun$startup$1(KafkaRaftServer.scala:95)
        at kafka.server.KafkaRaftServer.$anonfun$startup$1$adapted(KafkaRaftServer.scala:95)
        at scala.Option.foreach(Option.scala:407)
        at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:95)
        at kafka.Kafka$.main(Kafka.scala:113)
```

### What is the expected behavior?

Expected behaviour is the JAAS config to be passed properly.

On my local Kafka which I installed on my machine I can set this with no problem by executing the following command:
`export KAFKA_OPTS=-Djava.security.auth.login.config=config/kraft/kafka_server_jaas.conf` 

### What do you see instead?

An error message indicating the JAAS config is not set properly.

### Additional information

I'm using podman-compose although I doubt this is the problem.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
