### ISSUE TITLE
[bitnami/kafka] KeeperErrorCode = NoAuth for /consumers

### ISSUE THREAD

**Issue by dadiYazZ** [bitnami/containers#54845]
### Name and Version

latest

### What architecture are you using?

None

### What steps will reproduce the bug?

This is my Docker Compose
```
version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '12181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=myuser,user2
      - ZOO_SERVER_PASSWORDS=mypassword,pass4user2
      - ZOO_CLIENT_USER=myuser
      - ZOO_CLIENT_PASSWORD=mypassword
    volumes:
      - ./zookeeper_data:/bitnami/zookeeper


  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_USER=myuser
      - KAFKA_ZOOKEEPER_PASSWORD=mypassword
      - KAFKA_CLIENT_USERS=myuser
      - KAFKA_CLIENT_PASSWORDS=mypassword
    volumes:
      - ./kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper
```
This kind of problem occurs

### What do you see instead?
```
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /consumers
at org.apache.zookeeper.KeeperException.create(KeeperException.java:120)
at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
at kafka.zookeeper.AsyncResponse.maybeThrow(ZooKeeperClient.scala:570)
at kafka.zk.KafkaZkClient.createRecursive(KafkaZkClient.scala:1883)
at kafka.zk.KafkaZkClient.makeSurePersistentPathExists(KafkaZkClient.scala:1781)
at kafka.zk.KafkaZkClient.$anonfun$createTopLevelPaths$1(KafkaZkClient.scala:1773)
at kafka.zk.KafkaZkClient.$anonfun$createTopLevelPaths$1$adapted(KafkaZkClient.scala:1773)
at scala.collection.immutable.List.foreach(List.scala:431)
at kafka.zk.KafkaZkClient.createTopLevelPaths(KafkaZkClient.scala:1773)
at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:659)
at kafka.server.KafkaServer.startup(KafkaServer.scala:222)
at kafka.Kafka$.main(Kafka.scala:113)
at kafka.Kafka.main(Kafka.scala)
```

**Comment by Mauraza** [comment]
Hi @dadiYazZ,

Did you check this comment https://github.com/bitnami/charts/issues/3572#issuecomment-740095935?
