### ISSUE TITLE
bitnami/kafka:3.3 crash at startup

### ISSUE THREAD

**Issue by YiuRULE** [bitnami/containers#55303]
### Name and Version

bitnami/kafka:3.3

### What architecture are you using?

None

### What steps will reproduce the bug?

It can be reproduced using:
```
$ docker run \
    -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092 \
    -e ALLOW_PLAINTEXT_LISTENER=yes
    -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 \
    -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092 \
    bitnami/kafka:3.3
```

### What is the expected behavior?

With a zookeeper container who runs on the same docker network, the container should runs as usual

### What do you see instead?

```
[2024-01-23 03:12:54,232] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration message.max.bytes: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:742)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:146)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1492)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1495)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1418)
	at kafka.Kafka$.buildServer(Kafka.scala:67)
	at kafka.Kafka$.main(Kafka.scala:87)
	at kafka.Kafka.main(Kafka.scala)
```

**Comment by YiuRULE** [comment]
duplicated of https://github.com/bitnami/containers/issues/55274, I will close it
