### ISSUE TITLE
[ISSUE-240123] - bitnami/kafka:latest Invalid value  for configuration message.max.bytes

### ISSUE THREAD

**Issue by lavistta01** [bitnami/containers#55308]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

bitnami/kafka:latest

Got issue with "Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value  for configuration message.max.bytes: Not a number of type INT"

![image](https://github.com/bitnami/containers/assets/54022536/88eedee9-5df5-463f-97cc-c790ba3b887e)

### What do you see instead?

kafka 08:35:24.22 INFO  ==> Formatting storage directories to add metadata...
2024-01-23T08:35:25.147407949Z Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value  for configuration message.max.bytes: Not a number of type INT
2024-01-23T08:35:25.147664960Z 	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:745)
2024-01-23T08:35:25.147678796Z 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:493)
2024-01-23T08:35:25.147682884Z 	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:486)
2024-01-23T08:35:25.147685208Z 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:112)
2024-01-23T08:35:25.147773894Z 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:145)
2024-01-23T08:35:25.147780206Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1601)
2024-01-23T08:35:25.147782390Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1603)
2024-01-23T08:35:25.147810728Z 	at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:50)
2024-01-23T08:35:25.147873261Z 	at scala.Option.flatMap(Option.scala:271)
2024-01-23T08:35:25.147903507Z 	at kafka.tools.StorageTool$.main(StorageTool.scala:50)
2024-01-23T08:35:25.147944103Z 	at kafka.tools.StorageTool.main(StorageTool.scala)

**Comment by ipreina** [comment]
I have the same issue.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. Closing it as a duplicate of https://github.com/bitnami/containers/issues/55307. Let's continue the conversation there.

**Comment by lavistta01** [comment]
> Hi!
> 
> Thank you so much for opening the ticket. Closing it as a duplicate of #55307. Let's continue the conversation there.

Many thank Mr Javsalgar
