### ISSUE TITLE
[bitnami/airflow]: airflow.providers.cnf provider removed from airflow 2.8.1

### ISSUE THREAD

**Issue by alekseyolg** [bitnami/containers#55913]
### Name and Version

bitnami/airflow-[scheduler,worker]:2.8.1-debian-11-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

0. Before this I used images version 2.8.0 and chart 16.1.10
1. deploy helm chart bitnami/airflow:16.5.1 in kubernetes (any version) with images bitnami/airflow-[scheduler,worker]:2.8.1-debian-11-r2
2. executor: KubernetesExecutor

### What is the expected behavior?

Correct operation of all modules.

### What do you see instead?

```
[38;5;6mairflow-scheduler [38;5;5m14:18:11.50 [0m[38;5;2mINFO [0m ==> 
[38;5;6mairflow-scheduler [38;5;5m14:18:11.50 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami airflow-scheduler container[0m
[38;5;6mairflow-scheduler [38;5;5m14:18:11.50 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mairflow-scheduler [38;5;5m14:18:11.50 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mairflow-scheduler [38;5;5m14:18:11.50 [0m[38;5;2mINFO [0m ==> 
[38;5;6mairflow-scheduler [38;5;5m14:18:11.51 [0m[38;5;2mINFO [0m ==> Enabling non-root system user with nss_wrapper
[38;5;6mairflow-scheduler [38;5;5m14:18:11.51 [0m[38;5;2mINFO [0m ==> ** Starting Airflow setup **
[38;5;6mairflow-scheduler [38;5;5m14:18:11.55 [0m[38;5;2mINFO [0m ==> No injected configuration file found. Creating default config file
[38;5;6mairflow-scheduler [38;5;5m14:18:13.43 [0m[38;5;2mINFO [0m ==> Configuring Airflow database
[38;5;6mairflow-scheduler [38;5;5m14:18:13.45 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
[38;5;6mairflow-scheduler [38;5;5m14:18:15.45 [0m[38;5;2mINFO [0m ==> Waiting for Airflow Webserver to be up
[38;5;6mairflow-scheduler [38;5;5m14:18:15.46 [0m[38;5;2mINFO [0m ==> ** Airflow setup finished! **

[38;5;6mairflow-scheduler [38;5;5m14:18:15.49 [0m[38;5;2mINFO [0m ==> ** Starting Airflow **
/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/configuration.py:761 FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.
/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py:926 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[[34m2024-01-31T14:18:16.479+0000[0m] {[34mcli_parser.py:[0m64} ERROR[0m - Failed to load CLI commands from executor: KubernetesExecutor[0m
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/cli/cli_parser.py", line 60, in <module>
    executor, _ = ExecutorLoader.import_default_executor_cls(validate=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 167, in import_default_executor_cls
    executor, source = cls.import_executor_cls(executor_name, validate=validate)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 141, in import_executor_cls
    return _import_and_validate(cls.executors[executor_name]), ConnectorSource.CORE
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 135, in _import_and_validate
    executor = import_string(path)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.cncf'
[[34m2024-01-31T14:18:16.481+0000[0m] {[34mcli_parser.py:[0m65} ERROR[0m - Ensure all dependencies are met and try again. If using a Celery based executor install a 3.3.0+ version of the Celery provider. If using a Kubernetes executor, install a 7.4.0+ version of the CNCF provider[0m
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[[34m2024-01-31T14:18:17.485+0000[0m] {[34mtask_context_logger.py:[0m63} INFO[0m - Task context logging is enabled[0m
[[34m2024-01-31T14:18:17.486+0000[0m] {[34mexecutor_loader.py:[0m110} ERROR[0m - No module named 'airflow.providers.cncf'[0m
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 107, in load_executor
    executor_cls, import_source = cls.import_executor_cls(executor_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 141, in import_executor_cls
    return _import_and_validate(cls.executors[executor_name]), ConnectorSource.CORE
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 135, in _import_and_validate
    executor = import_string(path)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.cncf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/scheduler_command.py", line 67, in scheduler
    run_command_with_daemon_option(
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/scheduler_command.py", line 70, in <lambda>
    callback=lambda: _run_scheduler_job(args),
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/scheduler_command.py", line 44, in _run_scheduler_job
    ExecutorLoader.validate_database_executor_compatibility(job_runner.job.executor)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/jobs/job.py", line 123, in executor
    return ExecutorLoader.get_default_executor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 87, in get_default_executor
    return cls.load_executor(cls.get_default_executor_name())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/executors/executor_loader.py", line 111, in load_executor
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: The module/attribute could not be loaded. Please check "executor" key in "core" section. Current value: "KubernetesExecutor".
```

### Additional information

I also noticed that many Airflow modules that users often need for their work have been removed.

```
apache-airflow-providers-apache-cassandra
apache-airflow-providers-apache-drill
apache-airflow-providers-apache-druid
apache-airflow-providers-apache-hdfs
apache-airflow-providers-apache-hive
apache-airflow-providers-apache-impala
apache-airflow-providers-apache-pinot
apache-airflow-providers-arangodb
apache-airflow-providers-common-io
apache-airflow-providers-cloudant
apache-airflow-providers-cncf-kubernetes
apache-airflow-providers-databricks
apache-airflow-providers-exasol
apache-airflow-providers-influxdb
apache-airflow-providers-microsoft-azure
apache-airflow-providers-microsoft-mssql
apache-airflow-providers-mongo
apache-airflow-providers-neoj
apache-airflow-providers-presto
apache-airflow-providers-trino
apache-airflow-providers-vertica
sphinx-airflow-theme 
```

**Comment by Mauraza** [comment]
Hi @alekseyolg,

Could you add more information so I can replicate this issue?

**Comment by alekseyolg** [comment]
@Mauraza Of course, here is a complete list of data with which you can reproduce this problem!

```
extraEnvVars:
  - name: AIRFLOW__API__AUTH_BACKENDS
    value: "airflow.api.auth.backend.basic_auth"
  - name: AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS
    value: "True"

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true
  annotations: {}
rbac:
  create: true
executor: KubernetesExecutor
worker:
  automountServiceAccountToken: true
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 86400
    timeoutSeconds: 5
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 86400
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 1
    successThreshold: 1
web:
  automountServiceAccountToken: true
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
scheduler:
  automountServiceAccountToken: true
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 4
      memory: 8Gi
  podSecurityContext:
    enabled: false
    fsGroup: 1001
externalDatabase:
  host: pre-postgres-airflow
  port: 5432
  user: bn_airflow
  database: bitnami_airflow
  password: ""
  existingSecret: "postgresql"
  existingSecretPasswordKey: ""
```

**Comment by alekseyolg** [comment]
@Mauraza Moreover, this problem is confirmed by the fact that for some reason the provider was removed from the image itself, like many other providers!
If we compare the set of providers in the scheduler version 2.8.0 with version 2.8.1, we will see that there is a very big difference in their number.

I tried to get a list of providers in image v2.8.0:
```bash
docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.0-debian-11-r1 /opt/bitnami/airflow/venv/bin/pip freeze | grep airflow
apache-airflow==2.8.0
apache-airflow-providers-amazon==8.13.0
apache-airflow-providers-apache-cassandra==3.4.0
apache-airflow-providers-apache-drill==2.6.0
apache-airflow-providers-apache-druid==3.7.0
apache-airflow-providers-apache-hdfs==4.3.0
apache-airflow-providers-apache-hive==6.3.0
apache-airflow-providers-apache-impala==1.3.0
apache-airflow-providers-apache-pinot==4.3.0
apache-airflow-providers-arangodb==2.4.0
apache-airflow-providers-celery==3.5.0
apache-airflow-providers-cloudant==3.4.0
apache-airflow-providers-cncf-kubernetes==7.11.0
apache-airflow-providers-common-sql==1.9.0
apache-airflow-providers-databricks==5.0.0
apache-airflow-providers-docker==3.8.2
apache-airflow-providers-elasticsearch==5.3.0
apache-airflow-providers-exasol==4.4.0
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-google==10.12.0
apache-airflow-providers-grpc==3.4.0
apache-airflow-providers-hashicorp==3.6.0
apache-airflow-providers-http==4.8.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-influxdb==2.4.0
apache-airflow-providers-microsoft-azure==8.4.0
apache-airflow-providers-microsoft-mssql==3.6.0
apache-airflow-providers-mongo==3.5.0
apache-airflow-providers-mysql==5.5.0
apache-airflow-providers-neo4j==3.5.0
apache-airflow-providers-postgres==5.9.0
apache-airflow-providers-presto==5.3.0
apache-airflow-providers-redis==3.5.0
apache-airflow-providers-sendgrid==3.4.0
apache-airflow-providers-sftp==4.8.0
apache-airflow-providers-slack==8.5.0
apache-airflow-providers-sqlite==3.6.0
apache-airflow-providers-ssh==3.9.0
apache-airflow-providers-trino==5.5.0
apache-airflow-providers-vertica==3.7.0
google-cloud-orchestration-airflow==1.10.0
sphinx-airflow-theme==0.0.12
```

I successfully imported the kubernetes provider in v2.8.0:
(This is exactly the error with which the current version crashes when trying to launch the Kubernetes executor)
```bash
docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.0-debian-11-r1 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'airflow_version', 'annotations', 'packaging']
```
We see that the module is present and imported correctly.

Then I try to do all the same steps with v2.8.1:

```bash
docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.1-debian-11-r2 /opt/bitnami/airflow/venv/bin/pip freeze | grep airflow
apache-airflow==2.8.1
apache-airflow-providers-amazon==8.16.0
apache-airflow-providers-celery==3.5.1
apache-airflow-providers-common-io==1.2.0
apache-airflow-providers-common-sql==1.10.0
apache-airflow-providers-docker==3.9.1
apache-airflow-providers-elasticsearch==5.3.1
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-google==10.13.1
apache-airflow-providers-grpc==3.4.1
apache-airflow-providers-hashicorp==3.6.1
apache-airflow-providers-http==4.8.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-mysql==5.5.1
apache-airflow-providers-postgres==5.10.0
apache-airflow-providers-redis==3.6.0
apache-airflow-providers-sendgrid==3.4.0
apache-airflow-providers-sftp==4.8.1
apache-airflow-providers-slack==8.5.1
apache-airflow-providers-sqlite==3.7.0
apache-airflow-providers-ssh==3.10.0
google-cloud-orchestration-airflow==1.10.0
```
And finally, I try to import the kubernetes module. In fact, this is an attempt to reproduce the error that was attached at the very beginning of the topic, because the same module is imported there.

```bash
docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.1-debian-11-r2 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'airflow.providers.cncf'
```

Accordingly, from this we conclude that our image does not have the providers necessary for operation (obviously, because of this, images 2.8.0 have more weight than 2.8.1)

**Comment by alekseyolg** [comment]
@Mauraza 
Unfortunately, this problem is still being reproduced.
Below is the command to play it.

```
docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.1-debian-11-r3 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'
Unable to find image 'bitnami/airflow-scheduler:2.8.1-debian-11-r3' locally
2.8.1-debian-11-r3: Pulling from bitnami/airflow-scheduler
985a73d15db4: Pull complete
Digest: sha256:7e270e926dd0bce36c87f13e7b5aff293e11ae061fb7b36031aa3460b51a484a
Status: Downloaded newer image for bitnami/airflow-scheduler:2.8.1-debian-11-r3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'airflow.providers.cncf'
```

Also, I have to draw your attention to the fact that a number of airflow providers that are often used in work have also been removed from the images of version 2.8.1:
```
docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.0-debian-11-r1 /opt/bitnami/airflow/venv/bin/pip freeze | grep airflow | wc -l
42
docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.1-debian-11-r3 /opt/bitnami/airflow/venv/bin/pip freeze | grep airflow | wc -l
22
```

**Comment by migruiz4** [comment]
Hi @alekseyolg,

Indeed, while the patched airflow is present in the `bitnami/airflow` image, worker and scheduler images did not receive the patch for this bug:
```
$ docker run --rm -it --entrypoint='' bitnami/airflow:2.8.1-debian-11-r3 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'       
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'airflow_version', 'annotations', 'packaging']

$ docker run --rm -it --entrypoint='' bitnami/airflow-worker:2.8.1-debian-11-r3 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'airflow.providers.cncf'

$ docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.1-debian-11-r3 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'airflow.providers.cncf'
``` 

I have triggered a new release of the worker and scheduler images (`r4`) fixing this issue:
```
$ docker run --rm -it --entrypoint='' bitnami/airflow-worker:2.8.1-debian-11-r4 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'airflow_version', 'annotations', 'packaging']

$ docker run --rm -it --entrypoint='' bitnami/airflow-scheduler:2.8.1-debian-11-r4 /opt/bitnami/airflow/venv/bin/python -c 'from airflow.providers.cncf import kubernetes; print(dir(kubernetes))'
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'airflow_version', 'annotations', 'packaging']
```

I will also trigger a new release of the `bitnami/airflow` chart, thank you and sorry for the inconvenience.

**Comment by alekseyolg** [comment]
@migruiz4 Thanks for solving the problem!
