### ISSUE TITLE
[bitnami/kafka] Kafka service is not working when `KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM` is empty string

### ISSUE THREAD

**Issue by vkrasnolutskyi** [bitnami/containers#56656]
### Name and Version

bitnami/kafka:3.6

### What architecture are you using?

arm64

### What steps will reproduce the bug?

This is my config:
```
  kafka:
    container_name: ${COMPOSE_PROJECT_NAME}_kafka
    hostname: kafka.example.com
    image: bitnami/kafka:3.6
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: SASL_SSL://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      KAFKA_CFG_ADVERTISED_LISTENERS: SASL_SSL://${KAFKA_0_IP}:9092  # SASL_SSL://:9092
      KAFKA_CLIENT_USERS: user
      KAFKA_CLIENT_PASSWORDS: password
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_CONTROLLER_USER: controller_user
      KAFKA_CONTROLLER_PASSWORD: controller_password
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_USER: controller_user
      KAFKA_INTER_BROKER_PASSWORD: controller_password
      KAFKA_CERTIFICATE_PASSWORD: certificatePassword123
      KAFKA_TLS_TYPE: JKS  # or PEM
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''  # It must be empty. Disable common name verification
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_NUM_PARTITIONS: 10
      BITNAMI_DEBUG: yes
    volumes:
      - ./docker/kafka/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./docker/kafka/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
    ports:
      - "9092:9092"
    networks:
      net:
        ipv4_address: ${KAFKA_0_IP}
```

Using this config I'm not able to start the service.

If I remove `KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM` key or set any other value but not an empty string it starts well.

### What do you see instead?

When I start the service for the first time it crashes silently with no visible issue:
```
kafka 11:55:43.64 INFO  ==> 
2024-02-09T11:55:43.649935058Z kafka 11:55:43.64 INFO  ==> Welcome to the Bitnami kafka container
2024-02-09T11:55:43.655367933Z kafka 11:55:43.65 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
2024-02-09T11:55:43.655385516Z kafka 11:55:43.65 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
2024-02-09T11:55:43.655387225Z kafka 11:55:43.65 INFO  ==> 
2024-02-09T11:55:43.656959195Z kafka 11:55:43.65 INFO  ==> ** Starting Kafka setup **
2024-02-09T11:55:43.689693860Z kafka 11:55:43.68 DEBUG ==> Validating settings in KAFKA_* env vars...
2024-02-09T11:55:44.579644521Z kafka 11:55:44.57 INFO  ==> Initializing Kafka...
2024-02-09T11:55:44.582553877Z kafka 11:55:44.58 INFO  ==> No injected configuration files found, creating default config files
```

When I start it again it gives more logs before the crash:
```
kafka 11:59:16.18 INFO  ==> 
2024-02-09T11:59:16.188113448Z kafka 11:59:16.18 INFO  ==> Welcome to the Bitnami kafka container
2024-02-09T11:59:16.188645201Z kafka 11:59:16.18 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
2024-02-09T11:59:16.189444288Z kafka 11:59:16.18 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
2024-02-09T11:59:16.190965295Z kafka 11:59:16.19 INFO  ==> 
2024-02-09T11:59:16.191813507Z kafka 11:59:16.19 INFO  ==> ** Starting Kafka setup **
2024-02-09T11:59:16.232839280Z kafka 11:59:16.23 INFO  ==> Initializing KRaft storage metadata
2024-02-09T11:59:16.233621867Z kafka 11:59:16.23 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
2024-02-09T11:59:17.043245395Z kafka 11:59:17.04 INFO  ==> Generated Kafka cluster ID 'y3f4MwXCS2-SRjbRAiezkw'
2024-02-09T11:59:17.045324488Z kafka 11:59:17.04 INFO  ==> Formatting storage directories to add metadata...
2024-02-09T11:59:17.624681864Z Formatting /bitnami/kafka/data with metadata.version 3.6-IV2.
2024-02-09T11:59:18.027672011Z kafka 11:59:18.02 INFO  ==> ** Kafka setup finished! **
2024-02-09T11:59:18.028029430Z 
2024-02-09T11:59:18.043790794Z kafka 11:59:18.04 INFO  ==> ** Starting Kafka **
2024-02-09T11:59:18.377459327Z [2024-02-09 11:59:18,377] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
2024-02-09T11:59:18.514714415Z [2024-02-09 11:59:18,514] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
2024-02-09T11:59:18.592534398Z [2024-02-09 11:59:18,592] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
2024-02-09T11:59:18.593883446Z [2024-02-09 11:59:18,593] INFO [ControllerServer id=0] Starting controller (kafka.server.ControllerServer)
2024-02-09T11:59:18.604066243Z [2024-02-09 11:59:18,603] INFO authorizerStart completed for endpoint CONTROLLER. Endpoint is now READY. (org.apache.kafka.server.network.EndpointReadyFutures)
2024-02-09T11:59:18.754177307Z [2024-02-09 11:59:18,754] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
2024-02-09T11:59:18.769165001Z [2024-02-09 11:59:18,768] ERROR Encountered fatal fault: caught exception (org.apache.kafka.server.fault.ProcessTerminatingFaultHandler)
2024-02-09T11:59:18.769183001Z java.lang.IllegalArgumentException: Could not find a 'KafkaServer' or 'controller.KafkaServer' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
2024-02-09T11:59:18.769185376Z 	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:150)
2024-02-09T11:59:18.769187001Z 	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:103)
2024-02-09T11:59:18.769188209Z 	at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:74)
2024-02-09T11:59:18.769189376Z 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:143)
2024-02-09T11:59:18.769190543Z 	at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
2024-02-09T11:59:18.769191709Z 	at kafka.network.Processor.<init>(SocketServer.scala:973)
2024-02-09T11:59:18.769192918Z 	at kafka.network.Acceptor.newProcessor(SocketServer.scala:879)
2024-02-09T11:59:18.769194043Z 	at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:849)
2024-02-09T11:59:18.769195168Z 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
2024-02-09T11:59:18.769196668Z 	at kafka.network.Acceptor.addProcessors(SocketServer.scala:848)
2024-02-09T11:59:18.769197793Z 	at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:523)
2024-02-09T11:59:18.769198876Z 	at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:251)
2024-02-09T11:59:18.769200043Z 	at kafka.network.SocketServer.$anonfun$new$29(SocketServer.scala:172)
2024-02-09T11:59:18.769207959Z 	at kafka.network.SocketServer.$anonfun$new$29$adapted(SocketServer.scala:172)
2024-02-09T11:59:18.769209293Z 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
2024-02-09T11:59:18.769210376Z 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
2024-02-09T11:59:18.769211501Z 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
2024-02-09T11:59:18.769212584Z 	at kafka.network.SocketServer.<init>(SocketServer.scala:172)
2024-02-09T11:59:18.769213709Z 	at kafka.server.ControllerServer.startup(ControllerServer.scala:183)
2024-02-09T11:59:18.769214834Z 	at kafka.server.KafkaRaftServer.$anonfun$startup$1(KafkaRaftServer.scala:95)
2024-02-09T11:59:18.769215918Z 	at kafka.server.KafkaRaftServer.$anonfun$startup$1$adapted(KafkaRaftServer.scala:95)
2024-02-09T11:59:18.769217043Z 	at scala.Option.foreach(Option.scala:407)
2024-02-09T11:59:18.769218168Z 	at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:95)
2024-02-09T11:59:18.769219751Z 	at kafka.Kafka$.main(Kafka.scala:113)
2024-02-09T11:59:18.769220834Z 	at kafka.Kafka.main(Kafka.scala)
```

**Comment by vkrasnolutskyi** [comment]
Just discovered that it is happening only with `3.6.1` but not with `3.6.0`

**Comment by juan131** [comment]
Hi @vkrasnolutskyi 

I think this could be a consequence of the contribution below:

- https://github.com/bitnami/containers/pull/55276

Could you please confirm if you can reproduce the issue with version `3.6.1-debian-11-r2` (the version immediately previous to the changes)?

**Comment by vkrasnolutskyi** [comment]
for `3.6.1-debian-11-r2` if fails with a different issue:
```
kafka 15:24:59.56 INFO  ==> 
2024-02-16T15:24:59.563133326Z kafka 15:24:59.56 INFO  ==> Welcome to the Bitnami kafka container
2024-02-16T15:24:59.563843254Z kafka 15:24:59.56 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
2024-02-16T15:24:59.565055502Z kafka 15:24:59.56 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
2024-02-16T15:24:59.565759557Z kafka 15:24:59.56 INFO  ==> 
2024-02-16T15:24:59.570359824Z kafka 15:24:59.56 INFO  ==> ** Starting Kafka setup **
2024-02-16T15:25:00.612586175Z kafka 15:25:00.61 INFO  ==> Initializing Kafka...
2024-02-16T15:25:00.615484708Z kafka 15:25:00.61 INFO  ==> No injected configuration files found, creating default config files
2024-02-16T15:25:01.633446181Z kafka 15:25:01.63 INFO  ==> Initializing KRaft storage metadata
2024-02-16T15:25:01.634381549Z kafka 15:25:01.63 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
2024-02-16T15:25:02.413812424Z kafka 15:25:02.41 INFO  ==> Generated Kafka cluster ID 'Z2uuAAVBRVmalPWYUvonag'
2024-02-16T15:25:02.414756207Z kafka 15:25:02.41 INFO  ==> Adding KRaft SCRAM users at storage bootstrap
2024-02-16T15:25:02.420243366Z kafka 15:25:02.41 INFO  ==> Formatting storage directories to add metadata...
2024-02-16T15:25:02.925531683Z Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value  for configuration message.max.bytes: Not a number of type INT
2024-02-16T15:25:02.925647776Z 	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:745)
2024-02-16T15:25:02.925655649Z 	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:493)
2024-02-16T15:25:02.925657524Z 	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:486)
2024-02-16T15:25:02.925658898Z 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:112)
2024-02-16T15:25:02.925660273Z 	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:145)
2024-02-16T15:25:02.925661523Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1601)
2024-02-16T15:25:02.925662772Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1603)
2024-02-16T15:25:02.925663897Z 	at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:50)
2024-02-16T15:25:02.925674769Z 	at scala.Option.flatMap(Option.scala:271)
2024-02-16T15:25:02.925676227Z 	at kafka.tools.StorageTool$.main(StorageTool.scala:50)
2024-02-16T15:25:02.925771409Z 	at kafka.tools.StorageTool.main(StorageTool.scala)
```

**Comment by juan131** [comment]
Hi @vkrasnolutskyi 

Are you setting the `MESSAGE_MAX_BYTES` env. variable? The error is now complaining about using an invalid value for that setting.

**Comment by vkrasnolutskyi** [comment]
no, the config was not changed and is the same as in the bugreport

**Comment by juan131** [comment]
Ahhh sorry, I just realized it makes since the contribution I referred before was targeting the issue with `KAFKA_CFG_MESSAGE_MAX_BYTES` in particular. The thing is, by accepting that contribution we fixed that issue and we created this one.

I'll create a PR to address it.
