### ISSUE TITLE
Can't open Notebook Dashboard from jupyter-base-notebook using url and token

### ISSUE THREAD

**Issue by ahmedredahussien** [bitnami/containers#6291]
### Name and Version

containers/bitnami/jupyter-base-notebook:latest

### What steps will reproduce the bug?

1. create docker compose yaml file as below 
2. and run : docker-compose up -d
3. then check the container logs using : docker logs <jupyter container name or id>

**docker-compose.yaml** 
version: '2'

services:
  #------------------------jupyter----------------------------------
  jupyter-base-notebook:
    image: docker.io/bitnami/jupyter-base-notebook:1
    #command: [ "tail", "-f", "/dev/null" ]
    ports:
      - ${JUPYTER_PORT}:8888
    environment:
      - JUPYTERHUB_API_TOKEN=jupyter_token
      - CLIENT_ID=dre

### What is the expected behavior?

showing the token and the url of jupyter notebook user interface with the port 

### What do you see instead?

> docker logs dre-containers_jupyter-base-notebook_1
Traceback (most recent call last):
  File "/opt/bitnami/miniconda/bin/jupyterhub-singleuser", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 852, in initialize
    result = super().initialize(*args, **kwargs)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 573, in initialize
    return super().initialize(argv)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/notebook/notebookapp.py", line 2149, in initialize
    self.init_webapp()
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 610, in init_webapp
    self.init_hub_auth()
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 606, in init_hub_auth
    raise ValueError("Missing OAuth client ID")
ValueError: Missing OAuth client ID

**Comment by rafariossaa** [comment]
Hi,
  This container image is mainly used in our [jupyterhub chart](https://github.com/bitnami/charts/tree/master/bitnami/jupyterhub). If you want to run it in a docker compose, maybe you want to take a look to what the chart does.
