### ISSUE TITLE
[bitnami/keycloak] Fail to get theme in version 23+ since chart 20.0.0 is going readonly filesystem

### ISSUE THREAD

**Issue by AlexisDucastel** [bitnami/containers#64802]
### Name and Version

bitnami/keycloak:23.0.7-debian-12-r4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In several releases of keycloak deployed via Helm with chart "20.0.0", different clusters, different config, we have the template that is not loading, with this error in logs : 
```
2024-04-05 08:43:58,179 WARN  [org.keycloak.services] (executor-thread-1) KC-SERVICES0075: Failed to get theme request: java.lang.RuntimeException: Temporary directory /opt/bitnami/keycloak/bin/../data/tmp does not exist and it was not possible to create it.
2024-04-05T10:43:58.180068787+02:00 	at org.keycloak.quarkus.runtime.integration.QuarkusPlatform.getTmpDirectory(QuarkusPlatform.java:152)
2024-04-05T10:43:58.180072936+02:00 	at org.keycloak.encoding.GzipResourceEncodingProviderFactory.initCacheDir(GzipResourceEncodingProviderFactory.java:70)
2024-04-05T10:43:58.180075966+02:00 	at org.keycloak.encoding.GzipResourceEncodingProviderFactory.create(GzipResourceEncodingProviderFactory.java:29)
```

### What is the expected behavior?

The theme should load properly

### What do you see instead?

The theme is not loaded, leading to 500 HTTP error and unfunctional administration console (hopefully, login interface still works without theme, even if graphically-broken)

Admin :
<img width="304" alt="image" src="https://github.com/bitnami/containers/assets/1911945/2dd039e8-4f2a-4e39-b772-f4930ff9a9ec">

Login: 
<img width="345" alt="image" src="https://github.com/bitnami/containers/assets/1911945/c0efe5e4-fe23-4b0b-91a1-349ee0f8c7d4">

Account console:
<img width="1030" alt="image" src="https://github.com/bitnami/containers/assets/1911945/32b9431c-b464-48ed-a865-299f2594f968">

**Comment by AlexisDucastel** [comment]
Probably wrong place, posted in chart section instead : 
https://github.com/bitnami/charts/issues/24938
