### ISSUE TITLE
[bitnami/mlflow] MLFlow missing package: google-cloud-storage 

### ISSUE THREAD

**Issue by RussellSB** [bitnami/containers#65108]
### Name and Version

bitnami/mlflow

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Right now we have MLFlow setup with GCP and relying on the bitnami image. Whenever we try log ML models to the tracking server it tries saving it under the hood to google cloud storage but fails due to missing package `google-cloud-storage` and its dependencies (google.auth included). To reproduce simply without having to setup the whole GCP server;

1. Load mlflow bitnami image.
2. Start python
2. Interpret `from google.auth.exceptions import DefaultCredentialsError` (as per https://github.com/mlflow/mlflow/blob/master/mlflow/store/artifact/gcs_artifact_repo.py)

### What is the expected behavior?

It imports correctly.

### What do you see instead?

```
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/python/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 538, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 951, in _list_artifacts
    artifact_entities = _list_artifacts_for_proxied_run_artifact_root(
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 981, in _list_artifacts_for_proxied_run_artifact_root
    artifact_destination_repo = _get_artifact_repo_mlflow_artifacts()
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/server/handlers.py", line 175, in _get_artifact_repo_mlflow_artifacts
    _artifact_repo = get_artifact_repository(os.environ[ARTIFACTS_DESTINATION_ENV_VAR])
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 117, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 74, in get_artifact_repository
    return repository(artifact_uri)
  File "/opt/bitnami/python/lib/python3.10/site-packages/mlflow/store/artifact/gcs_artifact_repo.py", line 40, in __init__
    from google.auth.exceptions import DefaultCredentialsError
ModuleNotFoundError: No module named 'google.auth' 
```

### Additional information

As a work around we install `google-cloud-storage` over the image everytime the server is connected to, but would be good to have it in built in the image since it is core functionality. Would open a PR but not sure where to install this missing package in the repo.

This also seems related; https://github.com/bitnami/charts/issues/22720

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Indeed, these packages are missing. I created a task in our backlog to add these missing pip modules.

**Comment by RussellSB** [comment]
Great, thank you! Look forward to this,

**Comment by RussellSB** [comment]
Hey, are there any updates? Would be great to know how far down the roadmap this issue could be tackled.

**Comment by juan131** [comment]
Hi everyone

Could you please give it a try using the image tag `2.14.1-debian-12-r1`? We included the missing Python module on this image revision.
