### ISSUE TITLE
[bitnami/kafka] Kafka configuration parameters is NULL,

### ISSUE THREAD

**Issue by vladimircape** [bitnami/containers#65130]
### Name and Version

bitnami/kafka:3.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://${HOST_IP}:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_MAX_REQUEST_SIZE=16777216
      - KAFKA_CFG_MAX_MESSAGE_BYTES=16777216
      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES=16777216
      - KAFKA_CFG_MESSAGE_MAX_BYTES=16777216
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=16777216
      - FETCH_MESSAGE_MAX_BYTES=16777216
      - KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES=16777216

### What is the expected behavior?

/opt/bitnami/kafka/bin/kafka-configs.sh to see applied values

### What do you see instead?

server.properties|producer.properties] has the right value. But the output of /opt/bitnami/kafka/bin/kafka-configs.sh is still: max.request.size=null 

  fetch.message.max.bytes=null sensitive=true synonyms={STATIC_BROKER_CONFIG:fetch.message.max.bytes=null}
  max.message.bytes=null sensitive=true synonyms={STATIC_BROKER_CONFIG:max.message.bytes=null}
  max.partition.fetch.bytes=null sensitive=true synonyms={STATIC_BROKER_CONFIG:max.partition.fetch.bytes=null}
  max.request.size=null sensitive=true synonyms={STATIC_BROKER_CONFIG:max.request.size=null}

**Comment by juan131** [comment]
Hi @vladimircape 

Could you please share the container logs? It'd be great if you could add the environment variable `BITNAMI_DEBUG=true` to increase the verbosity.

**Comment by kapyaar** [comment]
Hi, 
May I add a similar issue that I am facing?

I am trying to test the log retention settings to make it delete older messages. For the test, I want to delete messages after 20 seconds. I am using the the following yml in docker.

```
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html/
    ports:
      - 8000:80
      - 8443:443
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1:delete --config=retention.ms=20000"
      # KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_MS: 20000
      KAFKA_LOG_ROLL_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
```

With this setting, I would expect that If I run a consumer to consume from the beginning, after 20 seconds, the consumer should not see this message. But it does. 

So, Took a look at 
`/opt/bitnami/kafka/bin$ kafka-configs.sh --bootstrap-server kafka:9092 --entity-type topics --entity-name test --describe --all`

And the values look like default settings. I am doing anything wrong?

**Comment by kapyaar** [comment]
OK, my bad. It turns out the variable names need to have an _CFG. I was using an old example which did not reflect this change. Even on docker hub, while the example yml shows this change, the section that talks about "Customizable Environmental Variables" still lists them without the _CFG.

**Comment by shad0w-jo4n** [comment]
I have the same issue on version 3.7

docker-compose:
```yaml
  kafka-0:
    image: docker.io/bitnami/kafka:3.7
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      BITNAMI_DEBUG: true
      # KRaft settings
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      # Listeners
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # Clustering
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - "./kafka_0_data:/bitnami/kafka"
```

output:
```
kafka 23:31:23.38 INFO  ==> 
2024-05-21T23:31:23.403288929Z kafka 23:31:23.39 INFO  ==> Welcome to the Bitnami kafka container
2024-05-21T23:31:23.415943388Z kafka 23:31:23.41 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
2024-05-21T23:31:23.428005013Z kafka 23:31:23.42 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
2024-05-21T23:31:23.439566763Z kafka 23:31:23.43 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
2024-05-21T23:31:23.450801721Z kafka 23:31:23.44 INFO  ==> 
2024-05-21T23:31:23.462280471Z kafka 23:31:23.45 INFO  ==> ** Starting Kafka setup **
2024-05-21T23:31:23.984457763Z kafka 23:31:23.98 DEBUG ==> Validating settings in KAFKA_* env vars...
2024-05-21T23:31:23.995550513Z kafka 23:31:23.99 WARN  ==> The KAFKA_ZOOKEEPER_PROTOCOL environment variable does not configure SASL and/or SSL, this setting is not recommended for production environments.
2024-05-21T23:31:24.134907013Z kafka 23:31:24.13 WARN  ==> Kafka has been configured with a PLAINTEXT listener, this setting is not recommended for production environments.
2024-05-21T23:31:24.240894513Z kafka 23:31:24.23 INFO  ==> Initializing Kafka...
2024-05-21T23:31:24.275466430Z kafka 23:31:24.27 INFO  ==> No injected configuration files found, creating default config files
2024-05-21T23:31:26.310623375Z kafka 23:31:26.30 INFO  ==> ** Kafka setup finished! **
2024-05-21T23:31:26.310958833Z 
2024-05-21T23:31:26.361731542Z kafka 23:31:26.35 INFO  ==> ** Starting Kafka **
2024-05-21T23:31:29.574579585Z [2024-05-21 23:31:29,574] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
2024-05-21T23:31:29.798747252Z [2024-05-21 23:31:29,798] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
2024-05-21T23:31:29.844280835Z [2024-05-21 23:31:29,842] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
2024-05-21T23:31:29.844312918Z java.lang.IllegalArgumentException: requirement failed: controller.listener.names must be empty when not running in KRaft mode: [CONTROLLER]
2024-05-21T23:31:29.844323877Z 	at scala.Predef$.require(Predef.scala:281)
2024-05-21T23:31:29.844325252Z 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2441)
2024-05-21T23:31:29.844326127Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2290)
2024-05-21T23:31:29.844327043Z 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1639)
2024-05-21T23:31:29.844328127Z 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1561)
2024-05-21T23:31:29.844328960Z 	at kafka.Kafka$.buildServer(Kafka.scala:71)
2024-05-21T23:31:29.844329710Z 	at kafka.Kafka$.main(Kafka.scala:90)
2024-05-21T23:31:29.844330502Z 	at kafka.Kafka.main(Kafka.scala)
```
