### ISSUE TITLE
[Odoo17] Impossible to log in to bitnami_odoo database

### ISSUE THREAD

**Issue by sergueikp** [bitnami/containers#65725]
### Describe your issue as much as you can

Hello, I'm testing bitnami odoo docker images.
I've created a container it is running, but I'm unable to log in to the default database, user: admin, password: bitnami.
Also when I create a new database it is not listed.
I've modified odoo.conf file to list_db = True, but it does not help.

Thank you!

**Comment by jotamartos** [comment]
I just transferred this issue to the bitnami/containers repo too. 

If you are using the default docker-compose.yml file we provide, it sets "bn_odoo" as database user and it does not configure a password (ALLOW_EMPTY_PASSWORD=yes). 

>I've modified odoo.conf file to list_db = True, but it does not help.

Please note that any change in the configuration will require the container to be restarted for the changes to take effect.

**Comment by mccarthysean** [comment]
I have this issue too. The environment variables are set properly, like ODOO_DATABASE_HOST, ODOO_DATABASE_USER, etc, but I'm getting the following error, even though I can get into the container and successfully connect to the "postgres" container with psql manually. 

```bash
2024-06-19 20:20:54,891 16 INFO ? odoo: Odoo version 17.0-20240605
2024-06-19 20:20:54,892 16 INFO ? odoo: addons paths: ['/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/addons', '/root/.local/share/Odoo/addons/17.0']
2024-06-19 20:20:54,892 16 INFO ? odoo: database: odoo@default:default
2024-06-19 20:20:54,892 16 INFO ? odoo.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/opt/bitnami/odoo/bin/odoo", line 4, in <module>
    __import__('pkg_resources').run_script('odoo==17.0.post20240605', 'odoo')
  File "/opt/bitnami/odoo/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 691, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/bitnami/odoo/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1530, in run_script
    exec(code, namespace, namespace)
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/EGG-INFO/scripts/odoo", line 8, in <module>
    odoo.cli.main()
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/cli/command.py", line 66, in main
    o.run(args)
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/cli/server.py", line 179, in run
    main(args)
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/cli/server.py", line 142, in main
    odoo.service.db._create_empty_database(db_name)
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/service/db.py", line 101, in _create_empty_database
    with closing(db.cursor()) as cr:
                 ^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/sql_db.py", line 752, in cursor
    return Cursor(self.__pool, self.__dbname, self.__dsn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/sql_db.py", line 267, in __init__
    self._cnx = pool.borrow(dsn)
                ^^^^^^^^^^^^^^^^
  File "<decorator-gen-13>", line 2, in borrow
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/lib/odoo-17.0.post20240605-py3.11.egg/odoo/sql_db.py", line 681, in borrow
    result = psycopg2.connect(
             ^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/odoo/venv/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?

Failed to initialize database. Exiting.
```
