### ISSUE TITLE
java.lang.UnsupportedClassVersionError when installing custom Elasticsearch plugin

### ISSUE THREAD

**Issue by natimellino** [bitnami/containers#71446]
### Name and Version

bitnami/elasticsearch:8.15.0-debian-12-r1

### What architecture are you using?

None

### What steps will reproduce the bug?

- Use a custom Dockerfile using the bitnami/elasticsearch base image to install ReadonlyRest plugin:

```Dockerfile
FROM bitnami/elasticsearch:8.15.0-debian-12-r1

USER root

COPY readonlyrest-1.59.0_es8.15.0.zip /tmp/readonlyrest-plugin.zip
RUN /opt/bitnami/elasticsearch/bin/elasticsearch-plugin install --batch file:///tmp/readonlyrest-plugin.zip
RUN /opt/bitnami/java/bin/java -jar /opt/bitnami/elasticsearch/plugins/readonlyrest/ror-tools.jar patch --es-path /opt/bitnami/elasticsearch
```
- Build the image and start Elasticsearch.

### What is the expected behavior?

Elasticsearch is up and running

### What do you see instead?

Elasticsearch fails to start:

```
elasticsearch 18:22:51.81 INFO  ==> ** Elasticsearch setup finished! **

elasticsearch 18:22:51.82 INFO  ==> ** Starting Elasticsearch **
warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/ESPolicy has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 61.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1095)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:741)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:665)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at org.elasticsearch.server@8.15.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase1(Elasticsearch.java:114)
        at org.elasticsearch.server@8.15.0/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:71)

ERROR: Elasticsearch died while starting up, with exit code 1
```

### Additional information

I think the error might be because of a mismatch between the Java version of the plugin and the Java version that the image uses (the plugin uses a newer version). Is there a way we could update the Java version in the image? Otherwise, I can't make it work to use this image with this plugin.

**Comment by carrodher** [comment]
The ElasticSearch container is bundled using Java 17.0.12, see https://github.com/bitnami/containers/blob/main/bitnami/elasticsearch/8/debian-12/Dockerfile#L35. Not sure what is the version used by the plugin. Could you check if the version used by the plugin matches the recommended Java version for ES?

**Comment by natimellino** [comment]
From what I could research from the error message that I showed you it seems that the plugin requires at least Java 18 to run (if I’m not mistaken)
