### ISSUE TITLE
[bitnami/mastodon] Container Exits on Precompiling Assets after version 4.2.10

### ISSUE THREAD

**Issue by PlaryWasTaken** [bitnami/containers#72458]
### Name and Version

bitnami:mastodon:4.2.10+

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Using the provided docker-compose try to setup a working compose instance of mastodon 4.2.10+
2. Container mastodon_1 exits prematurely having the last log as "Precompiling Assets"

### What do you see instead?

Container mastodon_1 exits prematurely having the last log as "Precompiling Assets"

**Comment by carrodher** [comment]
Hi,

Could you add the `BITNAMI_DEBUG=true` environment variable to increase the verbosity of the logs?

**Comment by PlaryWasTaken** [comment]
```mastodon 00:35:58.32 INFO  ==> Elasticsearch instance is ready
mastodon 00:35:58.32 INFO  ==> Migrating Elasticsearch
############################################################
WARN: You are risking to lose some changes during the reset.
      Please consider enabling journaling.
      See https://github.com/toptal/chewy#journaling
############################################################
No index specification was changed
Total: 0s
mastodon 00:36:01.15 INFO  ==> Creating admin user
mastodon 00:36:06.37 INFO  ==> Admin user already exists. Skipping
mastodon 00:36:06.39 INFO  ==> Mastodon application already initialized, restoring...
mastodon 00:36:06.45 INFO  ==> Precompiling assets
node:fs:1372
  const result = binding.mkdir(
                         ^

Error: EACCES: permission denied, mkdir '/.cache/node/corepack/v1'
    at mkdirSync (node:fs:1372:26)
    at getTemporaryFolder (/opt/bitnami/node/lib/node_modules/corepack/dist/lib/corepack.cjs:21486:27)
    at download (/opt/bitnami/node/lib/node_modules/corepack/dist/lib/corepack.cjs:21760:21)
    at installVersion (/opt/bitnami/node/lib/node_modules/corepack/dist/lib/corepack.cjs:21854:61)
    at async Engine.ensurePackageManager (/opt/bitnami/node/lib/node_modules/corepack/dist/lib/corepack.cjs:22310:32)
    at async Engine.executePackageManagerRequest (/opt/bitnami/node/lib/node_modules/corepack/dist/lib/corepack.cjs:22410:25)
    at async Object.runMain (/opt/bitnami/node/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/.cache/node/corepack/v1'
}

Node.js v20.17.0
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
Exiting!```
Trailing logs from the container

**Comment by carrodher** [comment]
It seems you need to grant the proper permissions at `/.cache/node`

**Comment by PlaryWasTaken** [comment]
That happens in a "clean" container so any permissions weren't changed by me, it could also be related to yarn not being installed as logged by corepack
