### ISSUE TITLE
Permission Denied when accessing /var/run/secrets/eks.amazonaws.com/serviceaccount/token

### ISSUE THREAD

**Issue by stevejr** [bitnami/containers#75359]
### Name and Version

bitnami/discourse:15.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy a new instance of discourse with chart version 15.0.5
2. Add the env var `DISCOURSE_EXTRA_CONF_CONTENT` with the string `s3_use_iam_profile = true` which instructs Discourse to use an IAM profile when accessing S3
3. Add all other Discourse values for accessing S3 i.e `s3_bucket` etc 
4. Use the default Security Context values for the Containers and Pods

### What is the expected behavior?

Discourse should start and be able to access the defined S3 bucket

### What do you see instead?

Discourse fails to start and logs the following error:

```
Errno::EACCES: Permission denied @ rb_sysopen - /var/run/secrets/eks.amazonaws.com/serviceaccount/token (Errno::EACCES)
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:90:in `read'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:90:in `_token_from_file'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:74:in `refresh'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/refreshing_credentials.rb:28:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:64:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:152:in `new'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:152:in `assume_role_web_identity_credentials'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:13:in `block in resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/aws-sdk-core/plugins/credentials_configuration.rb:73:in `block in <class:CredentialsConfiguration>'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:72:in `call'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:215:in `block in resolve_defaults'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:59:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:59:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:214:in `resolve_defaults'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:207:in `value_at'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:191:in `block in resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:191:in `resolve'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:179:in `apply_defaults'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/configuration.rb:152:in `build!'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/base.rb:65:in `build_config'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/base.rb:22:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.143.0/lib/aws-sdk-s3/client.rb:481:in `initialize'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.191.3/lib/seahorse/client/base.rb:102:in `new'
/opt/bitnami/discourse/lib/s3_helper.rb:392:in `init_aws_s3_client'
/opt/bitnami/discourse/lib/s3_helper.rb:285:in `s3_client'
/opt/bitnami/discourse/lib/s3_helper.rb:434:in `s3_resource'
/opt/bitnami/discourse/lib/s3_helper.rb:440:in `s3_bucket'
/opt/bitnami/discourse/lib/s3_helper.rb:70:in `upload'
/opt/bitnami/discourse/lib/file_store/s3_store.rb:118:in `store_file'
/opt/bitnami/discourse/lib/file_store/s3_store.rb:68:in `store_optimized_image'
/opt/bitnami/discourse/app/models/optimized_image.rb:120:in `block (2 levels) in create_for'
/opt/bitnami/discourse/app/models/optimized_image.rb:119:in `open'
/opt/bitnami/discourse/app/models/optimized_image.rb:119:in `block in create_for'
/opt/bitnami/discourse/app/models/optimized_image.rb:19:in `block (2 levels) in lock'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/app/models/optimized_image.rb:19:in `block in lock'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/app/models/optimized_image.rb:18:in `lock'
/opt/bitnami/discourse/app/models/optimized_image.rb:73:in `create_for'
/opt/bitnami/discourse/lib/site_icon_manager.rb:74:in `block in ensure_optimized!'
/opt/bitnami/discourse/lib/site_icon_manager.rb:70:in `each'
/opt/bitnami/discourse/lib/site_icon_manager.rb:70:in `ensure_optimized!'
/opt/bitnami/discourse/lib/tasks/db.rake:272:in `block (2 levels) in <main>'
/opt/bitnami/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/opt/bitnami/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/opt/bitnami/discourse/lib/tasks/db.rake:234:in `block in <main>'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:25:in `load'
/opt/bitnami/ruby/bin/bundle:25:in `<main>'
```

When accessing the Sidekiq container in the pod the default user is `root` which can read the file. If you `su - discourse` then you get the permission error.

### Additional information

Previous versions of Discourse are able to use an IAM Profile because they do not enforce a Security Context.

I have tried setting the Pod SecurityContext to have the `fsGroup` value set to `65534` but this still does not resolve the issue.

Please advise what the correct SecurityContext should be at both the Pod and Container level to allow the `discourse` user to be able to access the file.

**Comment by javsalgar** [comment]
Hi,

Could you try launching the chart diagnosticMode.enabled=true, then enter the container to see what exact permissions this file has?

**Comment by stevejr** [comment]
Hi @javsalgar,

File permissions as requested:
```
root@discourse-dev-7bc4b66c48-b24ml:/var/run/secrets/eks.amazonaws.com/serviceaccount# ls -ltra
total 0
lrwxrwxrwx 1 root root  12 Dec  5 11:15 token -> ..data/token
lrwxrwxrwx 1 root root  32 Dec  5 11:15 ..data -> ..2024_12_05_11_15_29.2322427820
drwxr-sr-x 2 root root  60 Dec  5 11:15 ..2024_12_05_11_15_29.2322427820
drwxrwsrwt 3 root root 100 Dec  5 11:15 .
drwxr-xr-x 3 root root  28 Dec  5 11:15 ..
root@discourse-dev-7bc4b66c48-b24ml:/var/run/secrets/eks.amazonaws.com/serviceaccount# ls -ltra ..data/token
-rw-r----- 1 root root 1029 Dec  5 11:15 ..data/token
```

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by stevejr** [comment]
Hi @carrodher, I am not sure I understand your response. As you can see the file is owned by the `root` user and is in the `root` group.

If I start changing the Security Context for the Pod or Container how will that affect the application as I am not 100% sure that Discourse doesn't need root permissions otherwise the default values in the Bitnami Helm Chart would not be setting them to run as root.

**Comment by stevejr** [comment]
I have tried changing the Pod Security Context so that the `fsGroup` is set to `65534` which is a known workaround but this is still not allowing access to the token file for the `discourse` user.

**Comment by stevejr** [comment]
@carrodher - This is an old response from you on another issue about Discourse - https://github.com/bitnami/containers/issues/63508#issuecomment-1980271983

Here you specifically mention that the Discourse container has to be built and run as root so I assume that is why the Security Context is set with the root id value. However, I have found that the image is built with some custom scripts that make sure the `discourse` user and group is created but the user is not added to any of the groups supplied in the Security Context so how would it ever read the token file?

- https://github.com/bitnami/containers/blob/501f4210a54fd40750a21664daaf0cbefa454175/bitnami/discourse/3/debian-12/rootfs/opt/bitnami/scripts/discourse/postunpack.sh#L23

**Comment by stevejr** [comment]
> Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.
> 
> For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
> 
> * [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
> * [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
> * [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
> * [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)
> 
> These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

Please note the comments in https://github.com/bitnami/charts/issues/24251#issue-2174100537 which say Discourse is not affected by the changes to run as non-root user 1001
