### ISSUE TITLE
Cassandra: Setting `ALLOW_EMPTY_PASSWORD=yes` produces invalid yaml

### ISSUE THREAD

**Issue by patdowney** [bitnami/containers#75745]
### Name and Version

bitnami/cassandra:5.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`docker run --env "ALLOW_EMPTY_PASSWORD=YES" bitnami/cassandra:5.0.2`

### What is the expected behavior?

```
...
cassandra 12:49:25.58 INFO  ==> Checking that it started up correctly
cassandra 12:50:30.68 INFO  ==> Found CQL startup log line
Picked up JAVA_TOOL_OPTIONS:
cassandra 12:50:31.53 INFO  ==> Nodetool reported the successful startup of cassandra
```

### What do you see instead?

```
...
cassandra 12:35:36.79 INFO  ==> Checking that it started up correctly
cassandra 12:43:57.78 ERROR ==> cassandra failed to start up
cassandra 12:43:57.78 ERROR ==> Log content
...
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Invalid yaml: file:/opt/bitnami/cassandra/conf/cassandra.yaml
org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml: file:/opt/bitnami/cassandra/conf/cassandra.yaml
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:146)
...
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:865)
Caused by: while parsing a block mapping
 in 'reader', line 29, column 1:
    cluster_name: 'My Cluster'
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 196, column 3:
      class_name: AllowAllAuthorizer
      ^
...
```

### Additional information

I think the issue is around https://github.com/bitnami/containers/blob/0e933d17083bc74e92b8df7a514f95d73758f1dd/bitnami/cassandra/5.0/debian-12/rootfs/opt/bitnami/scripts/libcassandra.sh#L572

The outcome of that transformation seems to change (from `/opt/bitnami/cassandra/conf.default/cassandra.yaml`):
```yaml
authorizer:
  class_name: AllowAllAuthorizer
```

into

```yaml
authorizer: 'AllowAllAuthorizer'
  class_name: AllowAllAuthorizer
```

So I think either that line is redundant, or needs some kind of conditional around it, perhaps inclusion in  the `-le 5` conditional directly above it

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by dlenskiSB** [comment]
This bug is definitely not "solved". 😮 

I identify the root cause here https://github.com/bitnami/containers/issues/76691

There is a one-character mistake in the default `cassandra.yaml` file included as part of the container, causing a parsing error when `ALLOW_EMPTY_PASSWORD=yes` is set. Very frustratingly, that default YAML file _does not appear to be part of the Git repository_, so it's impossible for me to open a PR against it.

**Comment by dlenskiSB** [comment]
Turns out that this is an upstream bug in the `cassandra.yaml` file distributed by `apache/cassandra` 🤕 
https://github.com/apache/cassandra/pull/3837

**Comment by smiklosovic** [comment]
fixed in Cassandra here https://github.com/apache/cassandra/commit/027689ae48e124dae66a064cc1766b1eef9ef20b
